region: ap-northeast-1
cluster: haguruma-worker-prod
service: haguruma-main-service-worker-prod
service_definition: ../services/worker/ecs-service-def.json # 使わないはずだが設定しないと動かないのでとりあえず service-worker を設定する
task_definition: null
timeout: 10m0s
