# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `mangrove` gem.
# Please instead update this file by running `bin/tapioca gem mangrove`.


# typed: true

# Mangrove
#
# source://mangrove//lib/mangrove/version.rb#4
module Mangrove; end

# source://mangrove//lib/mangrove/control_flow/control_signal.rb#5
module Mangrove::ControlFlow; end

# @abstract Subclasses must implement the `abstract` methods below.
#
# source://mangrove//lib/mangrove/control_flow/control_signal.rb#6
module Mangrove::ControlFlow::ControlSignal
  interface!

  # @abstract
  #
  # source://mangrove//lib/mangrove/control_flow/control_signal.rb#13
  sig { abstract.returns(T.untyped) }
  def inner_value; end
end

# source://mangrove//lib/mangrove/enum.rb#28
module Mangrove::Enum
  requires_ancestor { Module }

  # source://mangrove//lib/mangrove/enum.rb#35
  sig { params(block: T.proc.bind(::Mangrove::EnumVariantsScope).void).void }
  def variants(&block); end

  class << self
    # source://mangrove//lib/mangrove/enum.rb#90
    sig { params(receiver: T::Class[T.anything]).void }
    def extended(receiver); end
  end
end

# source://mangrove//lib/mangrove/enum.rb#7
class Mangrove::EnumVariantsScope
  # source://mangrove//lib/mangrove/enum.rb#12
  sig { params(parent: T::Class[T.anything]).void }
  def initialize(parent); end

  # source://mangrove//lib/mangrove/enum.rb#17
  sig { params(block: T.proc.void).void }
  def call(&block); end

  # source://mangrove//lib/mangrove/enum.rb#22
  sig { params(variant: T::Class[T.anything], inner_type: T.untyped).void }
  def variant(variant, inner_type); end
end

# Option is a type that represents either some value (`Some`) or no value (`None`).
#
# @abstract Subclasses must implement the `abstract` methods below.
#
# source://mangrove//lib/mangrove/option/control_signal.rb#7
module Mangrove::Option
  extend T::Generic
  include ::Kernel

  interface!
  sealed!

  InnerType = type_member

  # @abstract
  #
  # source://mangrove//lib/mangrove/option.rb#181
  sig { abstract.params(other: ::BasicObject).returns(T::Boolean) }
  def ==(other); end

  # @abstract
  #
  # source://mangrove//lib/mangrove/option.rb#190
  sig { abstract.params(message: ::String).returns(InnerType) }
  def expect!(message); end

  # @abstract
  #
  # source://mangrove//lib/mangrove/option.rb#193
  sig { abstract.params(block: T.proc.returns(T.untyped)).returns(InnerType) }
  def expect_with!(&block); end

  # @abstract
  #
  # source://mangrove//lib/mangrove/option.rb#202
  sig do
    abstract
      .type_parameters(:NewInnerType)
      .params(
        block: T.proc.params(inner: InnerType).returns(Mangrove::Option[T.type_parameter(:NewInnerType)])
      ).returns(Mangrove::Option[T.type_parameter(:NewInnerType)])
  end
  def map(&block); end

  # @abstract
  #
  # source://mangrove//lib/mangrove/option.rb#199
  sig { abstract.returns(T::Boolean) }
  def none?; end

  # @abstract
  #
  # source://mangrove//lib/mangrove/option.rb#205
  sig { abstract.params(default: Mangrove::Option[InnerType]).returns(Mangrove::Option[InnerType]) }
  def or(default); end

  # @abstract
  #
  # source://mangrove//lib/mangrove/option.rb#196
  sig { abstract.returns(T::Boolean) }
  def some?; end

  # @abstract
  #
  # source://mangrove//lib/mangrove/option.rb#208
  sig do
    abstract
      .type_parameters(:ErrType)
      .params(
        err: T.type_parameter(:ErrType)
      ).returns(Mangrove::Result[InnerType, T.type_parameter(:ErrType)])
  end
  def transpose(err); end

  # @abstract
  #
  # source://mangrove//lib/mangrove/option.rb#187
  sig { abstract.returns(InnerType) }
  def unwrap!; end

  # @abstract
  #
  # source://mangrove//lib/mangrove/option.rb#184
  sig { abstract.params(default: InnerType).returns(InnerType) }
  def unwrap_or(default); end

  class << self
    # source://mangrove//lib/mangrove/option.rb#25
    sig do
      type_parameters(:InnerType)
        .params(
          nilable: T.nilable(T.type_parameter(:InnerType))
        ).returns(Mangrove::Option[T.type_parameter(:InnerType)])
    end
    def from_nilable(nilable); end
  end
end

# source://mangrove//lib/mangrove/option/control_signal.rb#8
class Mangrove::Option::ControlSignal < ::StandardError
  include ::Mangrove::ControlFlow::ControlSignal

  # source://mangrove//lib/mangrove/option/control_signal.rb#14
  sig { params(inner_value: T.untyped).void }
  def initialize(inner_value); end

  # source://mangrove//lib/mangrove/option/control_signal.rb#20
  sig { override.params(other: ::BasicObject).returns(T::Boolean) }
  def ==(other); end

  # source://mangrove//lib/mangrove/option/control_signal.rb#30
  sig { override.returns(T.untyped) }
  def inner_value; end
end

# Option::None
#
# source://mangrove//lib/mangrove/option.rb#116
class Mangrove::Option::None
  extend T::Generic
  include ::Mangrove::Option

  InnerType = type_member

  # source://mangrove//lib/mangrove/option.rb#126
  sig { override.params(other: ::BasicObject).returns(T::Boolean) }
  def ==(other); end

  # @raise [Option::ControlSignal]
  #
  # source://mangrove//lib/mangrove/option.rb#149
  sig { override.params(message: ::String).returns(InnerType) }
  def expect!(message); end

  # @raise [Option::ControlSignal]
  #
  # source://mangrove//lib/mangrove/option.rb#154
  sig { override.params(block: T.proc.returns(T.untyped)).returns(InnerType) }
  def expect_with!(&block); end

  # source://mangrove//lib/mangrove/option.rb#165
  sig do
    override
      .type_parameters(:NewInnerType)
      .params(
        _block: T.proc.params(inner: InnerType).returns(Mangrove::Option[T.type_parameter(:NewInnerType)])
      ).returns(Mangrove::Option[T.type_parameter(:NewInnerType)])
  end
  def map(&_block); end

  # source://mangrove//lib/mangrove/option.rb#162
  sig { override.returns(T::Boolean) }
  def none?; end

  # source://mangrove//lib/mangrove/option.rb#170
  sig { override.params(default: Mangrove::Option[InnerType]).returns(Mangrove::Option[InnerType]) }
  def or(default); end

  # source://mangrove//lib/mangrove/option.rb#159
  sig { override.returns(T::Boolean) }
  def some?; end

  # source://mangrove//lib/mangrove/option.rb#175
  sig do
    override
      .type_parameters(:ErrType)
      .params(
        err: T.type_parameter(:ErrType)
      ).returns(Mangrove::Result[InnerType, T.type_parameter(:ErrType)])
  end
  def transpose(err); end

  # @raise [Option::ControlSignal]
  #
  # source://mangrove//lib/mangrove/option.rb#144
  sig { override.returns(InnerType) }
  def unwrap!; end

  # source://mangrove//lib/mangrove/option.rb#139
  sig { override.params(default: InnerType).returns(InnerType) }
  def unwrap_or(default); end
end

# Option::Some
#
# source://mangrove//lib/mangrove/option.rb#36
class Mangrove::Option::Some
  extend T::Generic
  include ::Mangrove::Option

  InnerType = type_member

  # source://mangrove//lib/mangrove/option.rb#46
  sig { params(inner: InnerType).void }
  def initialize(inner); end

  # source://mangrove//lib/mangrove/option.rb#51
  sig { override.params(other: ::BasicObject).returns(T::Boolean) }
  def ==(other); end

  # source://mangrove//lib/mangrove/option.rb#79
  sig { override.params(_message: ::String).returns(InnerType) }
  def expect!(_message); end

  # source://mangrove//lib/mangrove/option.rb#84
  sig { override.params(_block: T.proc.returns(T.untyped)).returns(InnerType) }
  def expect_with!(&_block); end

  # source://mangrove//lib/mangrove/option.rb#95
  sig do
    override
      .type_parameters(:NewInnerType)
      .params(
        block: T.proc.params(inner: InnerType).returns(Mangrove::Option[T.type_parameter(:NewInnerType)])
      ).returns(Mangrove::Option[T.type_parameter(:NewInnerType)])
  end
  def map(&block); end

  # source://mangrove//lib/mangrove/option.rb#92
  sig { override.returns(T::Boolean) }
  def none?; end

  # source://mangrove//lib/mangrove/option.rb#100
  sig { override.params(_default: Mangrove::Option[InnerType]).returns(Mangrove::Option[InnerType]) }
  def or(_default); end

  # source://mangrove//lib/mangrove/option.rb#89
  sig { override.returns(T::Boolean) }
  def some?; end

  # source://mangrove//lib/mangrove/option.rb#105
  sig do
    override
      .type_parameters(:ErrType)
      .params(
        _err: T.type_parameter(:ErrType)
      ).returns(Mangrove::Result[InnerType, T.type_parameter(:ErrType)])
  end
  def transpose(_err); end

  # source://mangrove//lib/mangrove/option.rb#64
  sig { returns(InnerType) }
  def unwrap; end

  # source://mangrove//lib/mangrove/option.rb#74
  sig { override.returns(InnerType) }
  def unwrap!; end

  # source://mangrove//lib/mangrove/option.rb#69
  sig { override.params(_default: InnerType).returns(InnerType) }
  def unwrap_or(_default); end

  private

  # source://mangrove//lib/mangrove/option.rb#112
  sig { returns(InnerType) }
  def inner; end
end

# Result is a type that represents either success (`Ok`) or failure (`Err`).
#
# @abstract Subclasses must implement the `abstract` methods below.
#
# source://mangrove//lib/mangrove/result/control_signal.rb#7
module Mangrove::Result
  extend T::Generic
  include ::Kernel

  interface!
  sealed!

  OkType = type_member
  ErrType = type_member

  # @abstract
  #
  # source://mangrove//lib/mangrove/result.rb#22
  sig { abstract.params(other: ::BasicObject).returns(T::Boolean) }
  def ==(other); end

  # @abstract
  #
  # source://mangrove//lib/mangrove/result.rb#70
  sig do
    abstract
      .type_parameters(:NewOkType)
      .params(
        other: Mangrove::Result[T.type_parameter(:NewOkType), ErrType]
      ).returns(Mangrove::Result[T.type_parameter(:NewOkType), ErrType])
  end
  def and(other); end

  # @abstract
  #
  # source://mangrove//lib/mangrove/result.rb#88
  sig do
    abstract
      .params(
        new_err_inner: ErrType,
        condition: T.proc.params(inner: OkType).returns(T::Boolean)
      ).returns(Mangrove::Result[OkType, ErrType])
  end
  def and_err_if(new_err_inner, &condition); end

  # @abstract
  #
  # source://mangrove//lib/mangrove/result.rb#73
  sig do
    abstract
      .type_parameters(:NewOkType)
      .params(
        block: T.proc.params(this: OkType).returns(Mangrove::Result[T.type_parameter(:NewOkType), ErrType])
      ).returns(Mangrove::Result[T.type_parameter(:NewOkType), ErrType])
  end
  def and_then(&block); end

  # @abstract
  #
  # source://mangrove//lib/mangrove/result.rb#76
  sig do
    abstract
      .type_parameters(:NewOkType)
      .params(
        _t_new_ok: T::Class[T.type_parameter(:NewOkType)],
        block: T.proc.params(this: OkType).returns(Mangrove::Result[T.type_parameter(:NewOkType), ErrType])
      ).returns(Mangrove::Result[T.type_parameter(:NewOkType), ErrType])
  end
  def and_then_wt(_t_new_ok, &block); end

  # @abstract
  # @deprecated Use #is_a?(Result::Err) instead to enable Sorbet to define types statically.
  #
  # source://mangrove//lib/mangrove/result.rb#31
  sig { abstract.returns(T::Boolean) }
  def err?; end

  # @abstract
  #
  # source://mangrove//lib/mangrove/result.rb#46
  sig { abstract.params(message: ::String).returns(OkType) }
  def expect!(message); end

  # @abstract
  #
  # source://mangrove//lib/mangrove/result.rb#49
  sig do
    abstract
      .type_parameters(:E)
      .params(
        block: T.proc.params(err: ErrType).returns(T.type_parameter(:E))
      ).returns(OkType)
  end
  def expect_with!(&block); end

  # @abstract
  #
  # source://mangrove//lib/mangrove/result.rb#52
  sig do
    abstract
      .type_parameters(:NewOkType, :NewErrType)
      .params(
        block: T.proc.params(this: Mangrove::Result[OkType, ErrType]).returns(Mangrove::Result[T.type_parameter(:NewOkType), T.type_parameter(:NewErrType)])
      ).returns(Mangrove::Result[T.type_parameter(:NewOkType), T.type_parameter(:NewErrType)])
  end
  def map(&block); end

  # @abstract
  #
  # source://mangrove//lib/mangrove/result.rb#64
  sig do
    abstract
      .type_parameters(:NewErrType)
      .params(
        block: T.proc.params(this: ErrType).returns(T.type_parameter(:NewErrType))
      ).returns(Mangrove::Result[OkType, T.type_parameter(:NewErrType)])
  end
  def map_err(&block); end

  # @abstract
  #
  # source://mangrove//lib/mangrove/result.rb#67
  sig do
    abstract
      .type_parameters(:NewErrType)
      .params(
        _t_new_err: T::Class[T.type_parameter(:NewErrType)],
        block: T.proc.params(this: ErrType).returns(T.type_parameter(:NewErrType))
      ).returns(Mangrove::Result[OkType, T.type_parameter(:NewErrType)])
  end
  def map_err_wt(_t_new_err, &block); end

  # @abstract
  #
  # source://mangrove//lib/mangrove/result.rb#58
  sig do
    abstract
      .type_parameters(:NewOkType)
      .params(
        block: T.proc.params(this: OkType).returns(T.type_parameter(:NewOkType))
      ).returns(Mangrove::Result[T.type_parameter(:NewOkType), ErrType])
  end
  def map_ok(&block); end

  # @abstract
  #
  # source://mangrove//lib/mangrove/result.rb#61
  sig do
    abstract
      .type_parameters(:NewOkType)
      .params(
        _t_new_ok: T::Class[T.type_parameter(:NewOkType)],
        block: T.proc.params(this: OkType).returns(T.type_parameter(:NewOkType))
      ).returns(Mangrove::Result[T.type_parameter(:NewOkType), ErrType])
  end
  def map_ok_wt(_t_new_ok, &block); end

  # @abstract
  #
  # source://mangrove//lib/mangrove/result.rb#55
  sig do
    abstract
      .type_parameters(:NewOkType, :NewErrType)
      .params(
        _t_new_ok: T::Class[T.type_parameter(:NewOkType)],
        _t_new_err: T::Class[T.type_parameter(:NewErrType)],
        block: T.proc.params(this: Mangrove::Result[OkType, ErrType]).returns(Mangrove::Result[T.type_parameter(:NewOkType), T.type_parameter(:NewErrType)])
      ).returns(Mangrove::Result[T.type_parameter(:NewOkType), T.type_parameter(:NewErrType)])
  end
  def map_wt(_t_new_ok, _t_new_err, &block); end

  # @abstract
  # @deprecated Use #is_a?(Result::Ok) instead to enable Sorbet to define types statically.
  #   This method will be removed in future versions.
  #
  # source://mangrove//lib/mangrove/result.rb#27
  sig { abstract.returns(T::Boolean) }
  def ok?; end

  # @abstract
  #
  # source://mangrove//lib/mangrove/result.rb#91
  sig { abstract.params(other: Mangrove::Result[OkType, ErrType]).returns(Mangrove::Result[OkType, ErrType]) }
  def or(other); end

  # @abstract
  #
  # source://mangrove//lib/mangrove/result.rb#94
  sig do
    abstract
      .type_parameters(:NewErrType)
      .params(
        block: T.proc.params(this: ErrType).returns(Mangrove::Result[OkType, T.type_parameter(:NewErrType)])
      ).returns(Mangrove::Result[OkType, T.type_parameter(:NewErrType)])
  end
  def or_else(&block); end

  # @abstract
  #
  # source://mangrove//lib/mangrove/result.rb#97
  sig do
    abstract
      .type_parameters(:NewErrType)
      .params(
        _t_new_err: T::Class[T.type_parameter(:NewErrType)],
        block: T.proc.params(this: ErrType).returns(Mangrove::Result[OkType, T.type_parameter(:NewErrType)])
      ).returns(Mangrove::Result[OkType, T.type_parameter(:NewErrType)])
  end
  def or_else_wt(_t_new_err, &block); end

  # @abstract
  #
  # source://mangrove//lib/mangrove/result.rb#109
  sig do
    abstract
      .params(
        new_ok_inner: OkType,
        condition: T.proc.params(inner: ErrType).returns(T::Boolean)
      ).returns(Mangrove::Result[OkType, ErrType])
  end
  def or_ok_if(new_ok_inner, &condition); end

  # @abstract
  #
  # source://mangrove//lib/mangrove/result.rb#34
  sig { abstract.returns(OkType) }
  def unwrap!; end

  # @abstract
  #
  # source://mangrove//lib/mangrove/result.rb#40
  sig { abstract.params(exception: ::Exception).returns(OkType) }
  def unwrap_or_raise!(exception); end

  # @abstract
  #
  # source://mangrove//lib/mangrove/result.rb#43
  sig { abstract.returns(OkType) }
  def unwrap_or_raise_inner!; end

  # @abstract
  #
  # source://mangrove//lib/mangrove/result.rb#37
  sig { abstract.params(block: T.proc.params(err: ErrType).returns(::Exception)).returns(OkType) }
  def unwrap_or_raise_with!(&block); end

  class << self
    extend T::Generic

    OkType = type_member
    ErrType = type_member
  end

  class << self
    # source://mangrove//lib/mangrove/result.rb#142
    sig do
      type_parameters(:ErrType)
        .params(
          inner: T.type_parameter(:ErrType)
        ).returns(Mangrove::Result::Err[T.untyped, T.type_parameter(:ErrType)])
    end
    def err(inner); end

    # source://mangrove//lib/mangrove/result.rb#147
    sig do
      type_parameters(:OkType, :ErrType)
        .params(
          _t_ok: T::Class[T.type_parameter(:OkType)],
          inner: T.type_parameter(:ErrType)
        ).returns(Mangrove::Result::Err[T.type_parameter(:OkType), T.type_parameter(:ErrType)])
    end
    def err_wt(_t_ok, inner); end

    # source://mangrove//lib/mangrove/result.rb#119
    sig do
      type_parameters(:T, :E)
        .params(
          results: T::Enumerable[Mangrove::Result[T.type_parameter(:T), T.type_parameter(:E)]]
        ).returns(Mangrove::Result[T::Enumerable[T.type_parameter(:T)], T::Enumerable[T.type_parameter(:E)]])
    end
    def from_results(results); end

    # source://mangrove//lib/mangrove/result.rb#132
    sig do
      type_parameters(:OkType)
        .params(
          inner: T.type_parameter(:OkType)
        ).returns(Mangrove::Result::Ok[T.type_parameter(:OkType), T.untyped])
    end
    def ok(inner); end

    # source://mangrove//lib/mangrove/result.rb#137
    sig do
      type_parameters(:OkType, :ErrType)
        .params(
          inner: T.type_parameter(:OkType),
          _t_err: T::Class[T.type_parameter(:ErrType)]
        ).returns(Mangrove::Result::Ok[T.type_parameter(:OkType), T.type_parameter(:ErrType)])
    end
    def ok_wt(inner, _t_err); end
  end
end

# source://mangrove//lib/mangrove/result/control_signal.rb#8
class Mangrove::Result::ControlSignal < ::StandardError
  include ::Mangrove::ControlFlow::ControlSignal

  # source://mangrove//lib/mangrove/result/control_signal.rb#14
  sig { params(inner_value: T.untyped).void }
  def initialize(inner_value); end

  # source://mangrove//lib/mangrove/result/control_signal.rb#20
  sig { override.params(other: ::BasicObject).returns(T::Boolean) }
  def ==(other); end

  # source://mangrove//lib/mangrove/result/control_signal.rb#30
  sig { override.returns(T.untyped) }
  def inner_value; end
end

# source://mangrove//lib/mangrove/result.rb#323
class Mangrove::Result::Err
  extend T::Generic
  include ::Mangrove::Result

  OkType = type_member
  ErrType = type_member

  # source://mangrove//lib/mangrove/result.rb#334
  sig { params(inner: ErrType).void }
  def initialize(inner); end

  # source://mangrove//lib/mangrove/result.rb#339
  sig { override.params(other: ::BasicObject).returns(T::Boolean) }
  def ==(other); end

  # source://mangrove//lib/mangrove/result.rb#427
  sig do
    override
      .type_parameters(:NewOkType)
      .params(
        _other: Mangrove::Result[T.type_parameter(:NewOkType), ErrType]
      ).returns(Mangrove::Result[T.type_parameter(:NewOkType), ErrType])
  end
  def and(_other); end

  # source://mangrove//lib/mangrove/result.rb#451
  sig do
    override
      .params(
        _new_err_inner: ErrType,
        _condition: T.proc.params(inner: OkType).returns(T::Boolean)
      ).returns(Mangrove::Result::Err[OkType, ErrType])
  end
  def and_err_if(_new_err_inner, &_condition); end

  # source://mangrove//lib/mangrove/result.rb#432
  sig do
    override
      .type_parameters(:NewOkType)
      .params(
        _block: T.proc.params(this: OkType).returns(Mangrove::Result[T.type_parameter(:NewOkType), ErrType])
      ).returns(Mangrove::Result[T.type_parameter(:NewOkType), ErrType])
  end
  def and_then(&_block); end

  # source://mangrove//lib/mangrove/result.rb#437
  sig do
    override
      .type_parameters(:NewOkType)
      .params(
        _t_new_ok: T::Class[T.type_parameter(:NewOkType)],
        _block: T.proc.params(this: OkType).returns(Mangrove::Result[T.type_parameter(:NewOkType), ErrType])
      ).returns(Mangrove::Result[T.type_parameter(:NewOkType), ErrType])
  end
  def and_then_wt(_t_new_ok, &_block); end

  # @deprecated Use #is_a?(Result::Err) instead to enable Sorbet to define types statically.
  #
  # source://mangrove//lib/mangrove/result.rb#392
  sig { override.returns(T::Boolean) }
  def err?; end

  # source://mangrove//lib/mangrove/result.rb#352
  sig { returns(ErrType) }
  def err_inner; end

  # @raise [Result::ControlSignal]
  #
  # source://mangrove//lib/mangrove/result.rb#377
  sig { override.params(message: ::String).returns(OkType) }
  def expect!(message); end

  # @raise [Result::ControlSignal]
  #
  # source://mangrove//lib/mangrove/result.rb#382
  sig do
    override
      .type_parameters(:E)
      .params(
        block: T.proc.params(err: ErrType).returns(T.type_parameter(:E))
      ).returns(OkType)
  end
  def expect_with!(&block); end

  # source://mangrove//lib/mangrove/result.rb#395
  sig do
    override
      .type_parameters(:NewOkType, :NewErrType)
      .params(
        block: T.proc.params(this: Mangrove::Result[OkType, ErrType]).returns(Mangrove::Result[T.type_parameter(:NewOkType), T.type_parameter(:NewErrType)])
      ).returns(Mangrove::Result[T.type_parameter(:NewOkType), T.type_parameter(:NewErrType)])
  end
  def map(&block); end

  # source://mangrove//lib/mangrove/result.rb#416
  sig do
    override
      .type_parameters(:NewErrType)
      .params(
        block: T.proc.params(this: ErrType).returns(T.type_parameter(:NewErrType))
      ).returns(Mangrove::Result[OkType, T.type_parameter(:NewErrType)])
  end
  def map_err(&block); end

  # Because sorbet does not deduct types from return values well. This method takes a type of new inner values.
  #
  # source://mangrove//lib/mangrove/result.rb#422
  sig do
    override
      .type_parameters(:NewErrType)
      .params(
        _t_new_err: T::Class[T.type_parameter(:NewErrType)],
        block: T.proc.params(this: ErrType).returns(T.type_parameter(:NewErrType))
      ).returns(Mangrove::Result[OkType, T.type_parameter(:NewErrType)])
  end
  def map_err_wt(_t_new_err, &block); end

  # source://mangrove//lib/mangrove/result.rb#405
  sig do
    override
      .type_parameters(:NewOkType)
      .params(
        _block: T.proc.params(this: OkType).returns(T.type_parameter(:NewOkType))
      ).returns(Mangrove::Result[T.type_parameter(:NewOkType), ErrType])
  end
  def map_ok(&_block); end

  # Because sorbet does not deduct types from return values well. This method takes a type of new inner values.
  #
  # source://mangrove//lib/mangrove/result.rb#411
  sig do
    override
      .type_parameters(:NewOkType)
      .params(
        _t_new_ok: T::Class[T.type_parameter(:NewOkType)],
        _block: T.proc.params(this: OkType).returns(T.type_parameter(:NewOkType))
      ).returns(Mangrove::Result[T.type_parameter(:NewOkType), ErrType])
  end
  def map_ok_wt(_t_new_ok, &_block); end

  # source://mangrove//lib/mangrove/result.rb#400
  sig do
    override
      .type_parameters(:NewOkType, :NewErrType)
      .params(
        _t_new_ok: T::Class[T.type_parameter(:NewOkType)],
        _t_new_err: T::Class[T.type_parameter(:NewErrType)],
        block: T.proc.params(this: Mangrove::Result[OkType, ErrType]).returns(Mangrove::Result[T.type_parameter(:NewOkType), T.type_parameter(:NewErrType)])
      ).returns(Mangrove::Result[T.type_parameter(:NewOkType), T.type_parameter(:NewErrType)])
  end
  def map_wt(_t_new_ok, _t_new_err, &block); end

  # @deprecated Use #is_a?(Result::Ok) instead to enable Sorbet to define types statically.
  #
  # source://mangrove//lib/mangrove/result.rb#388
  sig { override.returns(T::Boolean) }
  def ok?; end

  # source://mangrove//lib/mangrove/result.rb#456
  sig { override.params(other: Mangrove::Result[OkType, ErrType]).returns(Mangrove::Result[OkType, ErrType]) }
  def or(other); end

  # source://mangrove//lib/mangrove/result.rb#461
  sig do
    override
      .type_parameters(:NewErrType)
      .params(
        block: T.proc.params(this: ErrType).returns(Mangrove::Result[OkType, T.type_parameter(:NewErrType)])
      ).returns(Mangrove::Result[OkType, T.type_parameter(:NewErrType)])
  end
  def or_else(&block); end

  # source://mangrove//lib/mangrove/result.rb#466
  sig do
    override
      .type_parameters(:NewErrType)
      .params(
        _t_new_err: T::Class[T.type_parameter(:NewErrType)],
        block: T.proc.params(this: ErrType).returns(Mangrove::Result[OkType, T.type_parameter(:NewErrType)])
      ).returns(Mangrove::Result[OkType, T.type_parameter(:NewErrType)])
  end
  def or_else_wt(_t_new_err, &block); end

  # source://mangrove//lib/mangrove/result.rb#480
  sig do
    override
      .params(
        new_ok_inner: OkType,
        condition: T.proc.params(inner: ErrType).returns(T::Boolean)
      ).returns(Mangrove::Result[OkType, ErrType])
  end
  def or_ok_if(new_ok_inner, &condition); end

  # source://mangrove//lib/mangrove/result.rb#489
  sig { returns(::String) }
  def to_s; end

  # @raise [Result::ControlSignal]
  #
  # source://mangrove//lib/mangrove/result.rb#357
  sig { override.returns(OkType) }
  def unwrap!; end

  # source://mangrove//lib/mangrove/result.rb#362
  sig { override.params(exception: ::Exception).returns(OkType) }
  def unwrap_or_raise!(exception); end

  # source://mangrove//lib/mangrove/result.rb#372
  sig { override.returns(OkType) }
  def unwrap_or_raise_inner!; end

  # source://mangrove//lib/mangrove/result.rb#367
  sig { override.params(block: T.proc.params(err: ErrType).returns(::Exception)).returns(OkType) }
  def unwrap_or_raise_with!(&block); end

  class << self
    sig do
      type_parameters(:ErrType)
        .params(
          inner: T.type_parameter(:ErrType)
        ).returns(Mangrove::Result::Err[T.untyped, T.type_parameter(:ErrType)])
    end
    def new(inner); end
  end
end

# source://mangrove//lib/mangrove/result.rb#152
class Mangrove::Result::Ok
  extend T::Generic
  include ::Mangrove::Result

  OkType = type_member
  ErrType = type_member

  # source://mangrove//lib/mangrove/result.rb#163
  sig { params(inner: OkType).void }
  def initialize(inner); end

  # source://mangrove//lib/mangrove/result.rb#168
  sig { override.params(other: ::BasicObject).returns(T::Boolean) }
  def ==(other); end

  # source://mangrove//lib/mangrove/result.rb#256
  sig do
    override
      .type_parameters(:NewOkType)
      .params(
        other: Mangrove::Result[T.type_parameter(:NewOkType), ErrType]
      ).returns(Mangrove::Result[T.type_parameter(:NewOkType), ErrType])
  end
  def and(other); end

  # source://mangrove//lib/mangrove/result.rb#280
  sig do
    override
      .params(
        new_err_inner: ErrType,
        condition: T.proc.params(inner: OkType).returns(T::Boolean)
      ).returns(Mangrove::Result[OkType, ErrType])
  end
  def and_err_if(new_err_inner, &condition); end

  # source://mangrove//lib/mangrove/result.rb#261
  sig do
    override
      .type_parameters(:NewOkType)
      .params(
        block: T.proc.params(this: OkType).returns(Mangrove::Result[T.type_parameter(:NewOkType), ErrType])
      ).returns(Mangrove::Result[T.type_parameter(:NewOkType), ErrType])
  end
  def and_then(&block); end

  # source://mangrove//lib/mangrove/result.rb#266
  sig do
    override
      .type_parameters(:NewOkType)
      .params(
        _t_new_ok: T::Class[T.type_parameter(:NewOkType)],
        block: T.proc.params(this: OkType).returns(Mangrove::Result[T.type_parameter(:NewOkType), ErrType])
      ).returns(Mangrove::Result[T.type_parameter(:NewOkType), ErrType])
  end
  def and_then_wt(_t_new_ok, &block); end

  # @deprecated Use #is_a?(Result::Err) instead to enable Sorbet to define types statically.
  #
  # source://mangrove//lib/mangrove/result.rb#221
  sig { override.returns(T::Boolean) }
  def err?; end

  # source://mangrove//lib/mangrove/result.rb#206
  sig { override.params(_message: ::String).returns(OkType) }
  def expect!(_message); end

  # source://mangrove//lib/mangrove/result.rb#211
  sig do
    override
      .type_parameters(:E)
      .params(
        _block: T.proc.params(err: ErrType).returns(T.type_parameter(:E))
      ).returns(OkType)
  end
  def expect_with!(&_block); end

  # source://mangrove//lib/mangrove/result.rb#224
  sig do
    override
      .type_parameters(:NewOkType, :NewErrType)
      .params(
        block: T.proc.params(this: Mangrove::Result[OkType, ErrType]).returns(Mangrove::Result[T.type_parameter(:NewOkType), T.type_parameter(:NewErrType)])
      ).returns(Mangrove::Result[T.type_parameter(:NewOkType), T.type_parameter(:NewErrType)])
  end
  def map(&block); end

  # source://mangrove//lib/mangrove/result.rb#245
  sig do
    override
      .type_parameters(:NewErrType)
      .params(
        _block: T.proc.params(this: ErrType).returns(T.type_parameter(:NewErrType))
      ).returns(Mangrove::Result[OkType, T.type_parameter(:NewErrType)])
  end
  def map_err(&_block); end

  # Because sorbet does not deduct types from return values well. This method takes a type of new inner values.
  #
  # source://mangrove//lib/mangrove/result.rb#251
  sig do
    override
      .type_parameters(:NewErrType)
      .params(
        _t_new_err: T::Class[T.type_parameter(:NewErrType)],
        _block: T.proc.params(this: ErrType).returns(T.type_parameter(:NewErrType))
      ).returns(Mangrove::Result[OkType, T.type_parameter(:NewErrType)])
  end
  def map_err_wt(_t_new_err, &_block); end

  # source://mangrove//lib/mangrove/result.rb#234
  sig do
    override
      .type_parameters(:NewOkType)
      .params(
        block: T.proc.params(this: OkType).returns(T.type_parameter(:NewOkType))
      ).returns(Mangrove::Result[T.type_parameter(:NewOkType), ErrType])
  end
  def map_ok(&block); end

  # Because sorbet does not deduct types from return values well. This method takes a type of new inner values.
  #
  # source://mangrove//lib/mangrove/result.rb#240
  sig do
    override
      .type_parameters(:NewOkType)
      .params(
        _t_new_ok: T::Class[T.type_parameter(:NewOkType)],
        block: T.proc.params(this: OkType).returns(T.type_parameter(:NewOkType))
      ).returns(Mangrove::Result[T.type_parameter(:NewOkType), ErrType])
  end
  def map_ok_wt(_t_new_ok, &block); end

  # source://mangrove//lib/mangrove/result.rb#229
  sig do
    override
      .type_parameters(:NewOkType, :NewErrType)
      .params(
        _t_new_ok: T::Class[T.type_parameter(:NewOkType)],
        _t_new_err: T::Class[T.type_parameter(:NewErrType)],
        block: T.proc.params(this: Mangrove::Result[OkType, ErrType]).returns(Mangrove::Result[T.type_parameter(:NewOkType), T.type_parameter(:NewErrType)])
      ).returns(Mangrove::Result[T.type_parameter(:NewOkType), T.type_parameter(:NewErrType)])
  end
  def map_wt(_t_new_ok, _t_new_err, &block); end

  # @deprecated Use #is_a?(Result::Ok) instead to enable Sorbet to define types statically.
  #
  # source://mangrove//lib/mangrove/result.rb#217
  sig { override.returns(T::Boolean) }
  def ok?; end

  # source://mangrove//lib/mangrove/result.rb#181
  sig { returns(OkType) }
  def ok_inner; end

  # source://mangrove//lib/mangrove/result.rb#289
  sig { override.params(_other: Mangrove::Result[OkType, ErrType]).returns(Mangrove::Result[OkType, ErrType]) }
  def or(_other); end

  # source://mangrove//lib/mangrove/result.rb#294
  sig do
    override
      .type_parameters(:NewErrType)
      .params(
        _block: T.proc.params(this: ErrType).returns(Mangrove::Result[OkType, T.type_parameter(:NewErrType)])
      ).returns(Mangrove::Result[OkType, T.type_parameter(:NewErrType)])
  end
  def or_else(&_block); end

  # source://mangrove//lib/mangrove/result.rb#299
  sig do
    override
      .type_parameters(:NewErrType)
      .params(
        _t_new_err: T::Class[T.type_parameter(:NewErrType)],
        _block: T.proc.params(this: ErrType).returns(Mangrove::Result[OkType, T.type_parameter(:NewErrType)])
      ).returns(Mangrove::Result[OkType, T.type_parameter(:NewErrType)])
  end
  def or_else_wt(_t_new_err, &_block); end

  # source://mangrove//lib/mangrove/result.rb#313
  sig do
    override
      .params(
        _new_ok_inner: OkType,
        _condition: T.proc.params(inner: ErrType).returns(T::Boolean)
      ).returns(Mangrove::Result::Ok[OkType, ErrType])
  end
  def or_ok_if(_new_ok_inner, &_condition); end

  # source://mangrove//lib/mangrove/result.rb#318
  sig { returns(::String) }
  def to_s; end

  # source://mangrove//lib/mangrove/result.rb#186
  sig { override.returns(OkType) }
  def unwrap!; end

  # source://mangrove//lib/mangrove/result.rb#191
  sig { override.params(_exception: ::Exception).returns(OkType) }
  def unwrap_or_raise!(_exception); end

  # source://mangrove//lib/mangrove/result.rb#201
  sig { override.returns(OkType) }
  def unwrap_or_raise_inner!; end

  # source://mangrove//lib/mangrove/result.rb#196
  sig { override.params(_block: T.proc.params(err: ErrType).returns(::Exception)).returns(OkType) }
  def unwrap_or_raise_with!(&_block); end

  class << self
    sig do
      type_parameters(:OkType)
        .params(
          inner: T.type_parameter(:OkType)
        ).returns(Mangrove::Result::Ok[T.type_parameter(:OkType), T.untyped])
    end
    def new(inner); end
  end
end

# source://mangrove//lib/mangrove/version.rb#5
Mangrove::VERSION = T.let(T.unsafe(nil), String)
