# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `parallel_split_test` gem.
# Please instead update this file by running `bin/tapioca gem parallel_split_test`.


# a cleaned up version of the RSpec runner, e.g. no drb support
#
# source://parallel_split_test//lib/parallel_split_test.rb#3
module ParallelSplitTest
  class << self
    # source://parallel_split_test//lib/parallel_split_test.rb#16
    def best_number_of_processes; end

    # source://parallel_split_test//lib/parallel_split_test.rb#12
    def choose_number_of_processes; end

    # Returns the value of attribute example_counter.
    #
    # source://parallel_split_test//lib/parallel_split_test.rb#5
    def example_counter; end

    # Sets the attribute example_counter
    #
    # @param value the value to set the attribute example_counter to.
    #
    # source://parallel_split_test//lib/parallel_split_test.rb#5
    def example_counter=(_arg0); end

    # Returns the value of attribute process_number.
    #
    # source://parallel_split_test//lib/parallel_split_test.rb#5
    def process_number; end

    # Sets the attribute process_number
    #
    # @param value the value to set the attribute process_number to.
    #
    # source://parallel_split_test//lib/parallel_split_test.rb#5
    def process_number=(_arg0); end

    # Returns the value of attribute processes.
    #
    # source://parallel_split_test//lib/parallel_split_test.rb#5
    def processes; end

    # Sets the attribute processes
    #
    # @param value the value to set the attribute processes to.
    #
    # source://parallel_split_test//lib/parallel_split_test.rb#5
    def processes=(_arg0); end

    # @return [Boolean]
    #
    # source://parallel_split_test//lib/parallel_split_test.rb#7
    def run_example?; end
  end
end
