# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rspec-request_describer` gem.
# Please instead update this file by running `bin/tapioca gem rspec-request_describer`.


# source://rspec-request_describer//lib/rspec/request_describer/version.rb#1
module RSpec; end

# source://rspec-request_describer//lib/rspec/request_describer/version.rb#2
module RSpec::RequestDescriber
  class << self
    # @private
    #
    # source://rspec-request_describer//lib/rspec/request_describer.rb#21
    def included(base); end
  end
end

# source://rspec-request_describer//lib/rspec/request_describer.rb#5
RSpec::RequestDescriber::RESERVED_HEADER_NAMES = T.let(T.unsafe(nil), Array)

# source://rspec-request_describer//lib/rspec/request_describer.rb#11
RSpec::RequestDescriber::SUPPORTED_METHODS = T.let(T.unsafe(nil), Array)

# source://rspec-request_describer//lib/rspec/request_describer/version.rb#3
RSpec::RequestDescriber::VERSION = T.let(T.unsafe(nil), String)
