# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `seed-fu` gem.
# Please instead update this file by running `bin/tapioca gem seed-fu`.


# source://seed-fu//lib/seed-fu.rb#34
class ActiveRecord::Base
  include ::ActiveModel::ForbiddenAttributesProtection
  include ::ActiveModel::AttributeAssignment
  include ::ActiveModel::Access
  include ::ActiveModel::Serialization
  extend ::SeedFu::ActiveRecordExtension
  extend ::ActiveRecord::Import::Connection
end

# source://seed-fu//lib/seed-fu/railtie.rb#1
module SeedFu
  # source://seed-fu//lib/seed-fu.rb#18
  def fixture_paths; end

  # source://seed-fu//lib/seed-fu.rb#18
  def fixture_paths=(val); end

  # source://seed-fu//lib/seed-fu.rb#13
  def quiet; end

  # source://seed-fu//lib/seed-fu.rb#13
  def quiet=(val); end

  class << self
    # source://seed-fu//lib/seed-fu.rb#18
    def fixture_paths; end

    # source://seed-fu//lib/seed-fu.rb#18
    def fixture_paths=(val); end

    # source://seed-fu//lib/seed-fu.rb#13
    def quiet; end

    # source://seed-fu//lib/seed-fu.rb#13
    def quiet=(val); end

    # Load seed data from files
    #
    # @param fixture_paths [Array] The paths to look for seed files in
    # @param filter [Regexp] If given, only filenames matching this expression will be loaded
    #
    # source://seed-fu//lib/seed-fu.rb#28
    def seed(fixture_paths = T.unsafe(nil), filter = T.unsafe(nil)); end
  end
end

# source://seed-fu//lib/seed-fu/active_record_extension.rb#2
module SeedFu::ActiveRecordExtension
  # Load some seed data. There are two ways to do this.
  #
  # Verbose syntax
  # --------------
  #
  # This will seed a single record. The `:id` parameter ensures that if a record already exists
  # in the database with the same id, then it will be updated with the name and age, rather
  # than created from scratch.
  #
  #     Person.seed(:id) do |s|
  #       s.id   = 1
  #       s.name = "Jon"
  #       s.age  = 21
  #     end
  #
  # Note that `:id` is the default attribute used to identify a seed, so it need not be
  # specified.
  #
  # Terse syntax
  # ------------
  #
  # This is a more succinct way to load multiple records. Note that both `:x` and `:y` are being
  # used to identify a seed here.
  #
  #     Point.seed(:x, :y,
  #       { :x => 3, :y => 10, :name => "Home" },
  #       { :x => 5, :y => 9,  :name => "Office" }
  #     )
  #
  # source://seed-fu//lib/seed-fu/active_record_extension.rb#31
  def seed(*args, &block); end

  # Has the same syntax as {#seed}, but if a record already exists with the same values for
  # constraining attributes, it will not be updated.
  #
  # @example
  #   Person.seed(:id, :id => 1, :name => "Jon") # => Record created
  #   Person.seed(:id, :id => 1, :name => "Bob") # => Name changed
  #   Person.seed_once(:id, :id => 1, :name => "Harry") # => Name *not* changed
  #
  # source://seed-fu//lib/seed-fu/active_record_extension.rb#42
  def seed_once(*args, &block); end

  private

  # source://seed-fu//lib/seed-fu/active_record_extension.rb#49
  def parse_seed_fu_args(args, block); end
end

# @private
#
# source://seed-fu//lib/seed-fu/block_hash.rb#3
class SeedFu::BlockHash
  # @return [BlockHash] a new instance of BlockHash
  #
  # source://seed-fu//lib/seed-fu/block_hash.rb#4
  def initialize(proc); end

  # source://seed-fu//lib/seed-fu/block_hash.rb#13
  def method_missing(method_name, *args, &block); end

  # source://seed-fu//lib/seed-fu/block_hash.rb#9
  def to_hash; end
end

# source://seed-fu//lib/seed-fu/railtie.rb#2
class SeedFu::Railtie < ::Rails::Railtie; end

# Runs seed files.
#
# It is not recommended to use this class directly. Instead, use {SeedFu.seed SeedFu.seed}, which creates
# an instead of {Runner} and calls {#run #run}.
#
# @see SeedFu.seed SeedFu.seed
#
# source://seed-fu//lib/seed-fu/runner.rb#11
class SeedFu::Runner
  # @param fixture_paths [Array<String>] The paths where fixtures are located. Will use
  #   `SeedFu.fixture_paths` if {nil}. If the argument is not an array, it will be wrapped by one.
  # @param filter [Regexp] If given, only seed files with a file name matching this pattern will
  #   be used
  # @return [Runner] a new instance of Runner
  #
  # source://seed-fu//lib/seed-fu/runner.rb#16
  def initialize(fixture_paths = T.unsafe(nil), filter = T.unsafe(nil)); end

  # Run the seed files.
  #
  # source://seed-fu//lib/seed-fu/runner.rb#22
  def run; end

  private

  # source://seed-fu//lib/seed-fu/runner.rb#63
  def filenames; end

  # source://seed-fu//lib/seed-fu/runner.rb#51
  def open(filename); end

  # source://seed-fu//lib/seed-fu/runner.rb#32
  def run_file(filename); end
end

# Creates or updates seed records with data.
#
# It is not recommended to use this class directly. Instead, use `Model.seed`, and `Model.seed_once`,
# where `Model` is your Active Record model.
#
# @see ActiveRecordExtension
#
# source://seed-fu//lib/seed-fu/seeder.rb#10
class SeedFu::Seeder
  # @option options
  # @option options
  # @param model_class [ActiveRecord::Base] The model to be seeded
  # @param constraints [Array<Symbol>] A list of attributes which identify a particular seed. If
  #   a record with these attributes already exists then it will be updated rather than created.
  # @param data [Array<Hash>] Each item in this array is a hash containing attributes for a
  #   particular record.
  # @param options [Hash]
  # @return [Seeder] a new instance of Seeder
  #
  # source://seed-fu//lib/seed-fu/seeder.rb#20
  def initialize(model_class, constraints, data, options = T.unsafe(nil)); end

  # Insert/update the records as appropriate. Validation is skipped while saving.
  #
  # @return [Array<ActiveRecord::Base>] The records which have been seeded
  #
  # source://seed-fu//lib/seed-fu/seeder.rb#34
  def seed; end

  private

  # source://seed-fu//lib/seed-fu/seeder.rb#57
  def column_list(columns); end

  # source://seed-fu//lib/seed-fu/seeder.rb#83
  def constraint_conditions(data); end

  # source://seed-fu//lib/seed-fu/seeder.rb#78
  def find_or_initialize_record(data); end

  # source://seed-fu//lib/seed-fu/seeder.rb#61
  def seed_record(data); end

  # source://seed-fu//lib/seed-fu/seeder.rb#87
  def update_id_sequence; end

  # source://seed-fu//lib/seed-fu/seeder.rb#44
  def validate_constraints!; end

  # @raise [ArgumentError]
  #
  # source://seed-fu//lib/seed-fu/seeder.rb#53
  def validate_data!; end
end

# The current version of Seed Fu
#
# source://seed-fu//lib/seed-fu/version.rb#3
SeedFu::VERSION = T.let(T.unsafe(nil), String)

# {Writer} is used to programmatically generated seed files. For example, you might want to write
# a script which converts data in a CSV file to a valid Seed Fu seed file, which can then be
# imported.
#
# @example Basic usage
#   SeedFu::Writer.write('path/to/file.rb', :class_name => 'Person', :constraints => [:first_name, :last_name]) do |writer|
#   writer.add(:first_name => 'Jon',   :last_name => 'Smith',    :age => 21)
#   writer.add(:first_name => 'Emily', :last_name => 'McDonald', :age => 24)
#   end
#
#   # Writes the following to the file:
#   #
#   # Person.seed(:first_name, :last_name,
#   #   {:first_name=>"Jon", :last_name=>"Smith", :age=>21},
#   #   {:first_name=>"Emily", :last_name=>"McDonald", :age=>24}
#   # )
#
# source://seed-fu//lib/seed-fu/writer.rb#18
class SeedFu::Writer
  # @option options
  # @option options
  # @option options
  # @option options
  # @param options [Hash]
  # @raise [ArgumentError]
  # @return [Writer] a new instance of Writer
  #
  # source://seed-fu//lib/seed-fu/writer.rb#34
  def initialize(options = T.unsafe(nil)); end

  # Add a seed. Must be called within a block passed to {#write}.
  #
  # @param seed [Hash] The attributes for the seed
  #
  # source://seed-fu//lib/seed-fu/writer.rb#67
  def <<(seed); end

  # Add a seed. Must be called within a block passed to {#write}.
  #
  # @param seed [Hash] The attributes for the seed
  #
  # source://seed-fu//lib/seed-fu/writer.rb#85
  def add(seed); end

  # source://seed-fu//lib/seed-fu/writer.rb#19
  def default_options; end

  # source://seed-fu//lib/seed-fu/writer.rb#19
  def default_options=(val); end

  # Writes the necessary headers and footers, and yields to a block within which the actual
  # seed data should be writting using the `#<<` method.
  #
  # @param io_or_filename [IO] The IO to which writes will be made. (If an `IO` is given, it is
  #   your responsibility to close it after writing.)
  # @param io_or_filename [String] The filename of a file to make writes to. (Will be opened and
  #   closed automatically.)
  # @raise [ArgumentError]
  # @yield [self] make calls to `#<<` within the block
  #
  # source://seed-fu//lib/seed-fu/writer.rb#53
  def write(io_or_filename, &block); end

  private

  # @return [Boolean]
  #
  # source://seed-fu//lib/seed-fu/writer.rb#128
  def chunk_this_seed?; end

  # source://seed-fu//lib/seed-fu/writer.rb#113
  def file_footer; end

  # source://seed-fu//lib/seed-fu/writer.rb#100
  def file_header; end

  # source://seed-fu//lib/seed-fu/writer.rb#124
  def seed_footer; end

  # source://seed-fu//lib/seed-fu/writer.rb#119
  def seed_header; end

  # source://seed-fu//lib/seed-fu/writer.rb#89
  def write_to_io(io); end

  class << self
    # source://seed-fu//lib/seed-fu/writer.rb#19
    def default_options; end

    # source://seed-fu//lib/seed-fu/writer.rb#19
    def default_options=(val); end

    # Creates a new instance of {Writer} with the `options`, and then calls {#write} with the
    # `io_or_filename` and `block`
    #
    # source://seed-fu//lib/seed-fu/writer.rb#41
    def write(io_or_filename, options = T.unsafe(nil), &block); end
  end
end
