# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sidekiq-status` gem.
# Please instead update this file by running `bin/tapioca gem sidekiq-status`.


# source://sidekiq-status//lib/sidekiq-status/client_middleware.rb#2
JOB_CLASS = Sidekiq::JobRecord

# source://sidekiq-status//lib/sidekiq-status/version.rb#1
module Sidekiq
  class << self
    # source://sidekiq-status//lib/sidekiq-status/sidekiq_extensions.rb#4
    def major_version; end
  end
end

# adapted from https://github.com/cryo28/sidekiq_status
#
# source://sidekiq-status//lib/sidekiq-status/version.rb#2
module Sidekiq::Status
  extend ::Sidekiq::Status::Storage

  class << self
    # Methods for retrieving job completion
    #
    # source://sidekiq-status//lib/sidekiq-status.rb#54
    def at(job_id); end

    # source://sidekiq-status//lib/sidekiq-status.rb#37
    def cancel(job_id, job_unix_time = T.unsafe(nil)); end

    # source://sidekiq-status//lib/sidekiq-status.rb#48
    def complete?(job_id); end

    # Helper method to easily configure sidekiq-status client middleware
    # whatever the Sidekiq version is.
    #
    # @option client_middleware_options
    # @param sidekiq_config [Sidekiq] the Sidekiq config
    # @param client_middleware_options [Hash] client middleware initialization options
    #
    # source://sidekiq-status//lib/sidekiq-status/client_middleware.rb#63
    def configure_client_middleware(sidekiq_config, client_middleware_options = T.unsafe(nil)); end

    # Helper method to easily configure sidekiq-status server middleware
    # whatever the Sidekiq version is.
    #
    # @option server_middleware_options
    # @param sidekiq_config [Sidekiq] the Sidekiq config
    # @param server_middleware_options [Hash] server middleware initialization options
    #
    # source://sidekiq-status//lib/sidekiq-status/server_middleware.rb#94
    def configure_server_middleware(sidekiq_config, server_middleware_options = T.unsafe(nil)); end

    # source://sidekiq-status//lib/sidekiq-status.rb#41
    def delete(job_id); end

    # source://sidekiq-status//lib/sidekiq-status.rb#74
    def eta(job_id); end

    # source://sidekiq-status//lib/sidekiq-status.rb#48
    def failed?(job_id); end

    # Job status by id
    #
    # @param id [String] job id returned by async_perform
    # @return [String] job status, possible values are in STATUS
    #
    # source://sidekiq-status//lib/sidekiq-status.rb#21
    def get(job_id, field); end

    # Get all status fields for a job
    #
    # @return [Hash] hash of all fields stored for the job
    #
    # source://sidekiq-status//lib/sidekiq-status.rb#28
    def get_all(job_id); end

    # source://sidekiq-status//lib/sidekiq-status.rb#48
    def interrupted?(job_id); end

    # source://sidekiq-status//lib/sidekiq-status.rb#81
    def message(job_id); end

    # source://sidekiq-status//lib/sidekiq-status.rb#62
    def pct_complete(job_id); end

    # source://sidekiq-status//lib/sidekiq-status.rb#48
    def queued?(job_id); end

    # source://sidekiq-status//lib/sidekiq-status.rb#93
    def redis_adapter; end

    # source://sidekiq-status//lib/sidekiq-status.rb#48
    def retrying?(job_id); end

    # source://sidekiq-status//lib/sidekiq-status.rb#32
    def status(job_id); end

    # source://sidekiq-status//lib/sidekiq-status.rb#48
    def stopped?(job_id); end

    # source://sidekiq-status//lib/sidekiq-status.rb#58
    def total(job_id); end

    # source://sidekiq-status//lib/sidekiq-status.rb#45
    def unschedule(job_id, job_unix_time = T.unsafe(nil)); end

    # source://sidekiq-status//lib/sidekiq-status.rb#70
    def update_time(job_id); end

    # source://sidekiq-status//lib/sidekiq-status.rb#48
    def working?(job_id); end

    # source://sidekiq-status//lib/sidekiq-status.rb#66
    def working_at(job_id); end

    # source://sidekiq-status//lib/sidekiq-status.rb#85
    def wrap_redis_connection(conn); end
  end
end

# Should be in the client middleware chain
#
# source://sidekiq-status//lib/sidekiq-status/client_middleware.rb#6
class Sidekiq::Status::ClientMiddleware
  include ::Sidekiq::Status::Storage

  # Parameterized initialization, use it when adding middleware to client chain
  # chain.add Sidekiq::Status::ClientMiddleware, :expiration => 60 * 5
  #
  # @option opts
  # @param opts [Hash] middleware initialization options
  # @return [ClientMiddleware] a new instance of ClientMiddleware
  #
  # source://sidekiq-status//lib/sidekiq-status/client_middleware.rb#13
  def initialize(opts = T.unsafe(nil)); end

  # Uses msg['jid'] id and puts :queued status in the job's Redis hash
  #
  # @param worker_class [Class] if includes Sidekiq::Status::Worker, the job gets processed with the plugin
  # @param msg [Array] job arguments
  # @param queue [String] the queue's name
  # @param redis_pool [ConnectionPool] optional redis connection pool
  #
  # source://sidekiq-status//lib/sidekiq-status/client_middleware.rb#22
  def call(worker_class, msg, queue, redis_pool = T.unsafe(nil)); end

  # source://sidekiq-status//lib/sidekiq-status/client_middleware.rb#49
  def display_args(msg, queue); end
end

# source://sidekiq-status//lib/sidekiq-status.rb#14
Sidekiq::Status::DEFAULT_EXPIRY = T.let(T.unsafe(nil), Integer)

# adapter for redis-rb client
#
# source://sidekiq-status//lib/sidekiq-status/redis_adapter.rb#2
class Sidekiq::Status::RedisAdapter
  # @return [RedisAdapter] a new instance of RedisAdapter
  #
  # source://sidekiq-status//lib/sidekiq-status/redis_adapter.rb#3
  def initialize(client); end

  # source://sidekiq-status//lib/sidekiq-status/redis_adapter.rb#15
  def method_missing(method, *args); end

  # source://sidekiq-status//lib/sidekiq-status/redis_adapter.rb#7
  def scan(**options, &block); end

  # source://sidekiq-status//lib/sidekiq-status/redis_adapter.rb#11
  def schedule_batch(key, options); end
end

# adapter for redis-client client
#
# source://sidekiq-status//lib/sidekiq-status/redis_client_adapter.rb#2
class Sidekiq::Status::RedisClientAdapter
  # @return [RedisClientAdapter] a new instance of RedisClientAdapter
  #
  # source://sidekiq-status//lib/sidekiq-status/redis_client_adapter.rb#3
  def initialize(client); end

  # source://sidekiq-status//lib/sidekiq-status/redis_client_adapter.rb#11
  def method_missing(method, *args); end

  # source://sidekiq-status//lib/sidekiq-status/redis_client_adapter.rb#7
  def schedule_batch(key, options); end
end

# source://sidekiq-status//lib/sidekiq-status.rb#15
Sidekiq::Status::STATUS = T.let(T.unsafe(nil), Array)

# Should be in the server middleware chain
#
# source://sidekiq-status//lib/sidekiq-status/server_middleware.rb#7
class Sidekiq::Status::ServerMiddleware
  include ::Sidekiq::Status::Storage

  # Parameterized initialization, use it when adding middleware to server chain
  # chain.add Sidekiq::Status::ServerMiddleware, :expiration => 60 * 5
  #
  # @option opts
  # @param opts [Hash] middleware initialization options
  # @return [ServerMiddleware] a new instance of ServerMiddleware
  #
  # source://sidekiq-status//lib/sidekiq-status/server_middleware.rb#17
  def initialize(opts = T.unsafe(nil)); end

  # Uses sidekiq's internal jid as id
  # puts :working status into Redis hash
  # initializes worker instance with id
  #
  # Exception handler sets :failed status, re-inserts worker and re-throws the exception
  # Worker::Stopped exception type are processed separately - :stopped status is set, no re-throwing
  #
  # @param worker [Worker] worker instance, processed here if its class includes Status::Worker
  # @param msg [Array] job args, should have jid format
  # @param queue [String] queue name
  #
  # source://sidekiq-status//lib/sidekiq-status/server_middleware.rb#31
  def call(worker, msg, queue); end

  private

  # source://sidekiq-status//lib/sidekiq-status/server_middleware.rb#72
  def retry_attempt_number(msg); end

  # source://sidekiq-status//lib/sidekiq-status/server_middleware.rb#80
  def retry_attempts_from(msg_retry, default); end

  # source://sidekiq-status//lib/sidekiq-status/server_middleware.rb#84
  def sidekiq_version_dependent_retry_offset; end
end

# source://sidekiq-status//lib/sidekiq-status/server_middleware.rb#9
Sidekiq::Status::ServerMiddleware::DEFAULT_MAX_RETRY_ATTEMPTS = T.let(T.unsafe(nil), Integer)

# source://sidekiq-status//lib/sidekiq-status/storage.rb#1
module Sidekiq::Status::Storage
  protected

  # Unschedules the job and deletes the Status
  #
  # @param id [String] job id
  # @param job_unix_time, [Num] unix timestamp for the scheduled job
  #
  # source://sidekiq-status//lib/sidekiq-status/storage.rb#39
  def delete_and_unschedule(job_id, job_unix_time = T.unsafe(nil)); end

  # Deletes status hash info for given job id
  # @param[String] job id
  #
  # source://sidekiq-status//lib/sidekiq-status/storage.rb#59
  def delete_status(id); end

  # Gets a single valued from job status hash
  #
  # @param id [String] job id
  # @param Symbol [String] field fetched field name
  # @return [String] Redis operation status code
  #
  # source://sidekiq-status//lib/sidekiq-status/storage.rb#69
  def read_field_for_id(id, field); end

  # Gets the whole status hash from the job status
  #
  # @param id [String] job id
  # @return [Hash] Hash stored in redis
  #
  # source://sidekiq-status//lib/sidekiq-status/storage.rb#78
  def read_hash_for_id(id); end

  # Stores multiple values into a job's status hash,
  # sets last update time
  #
  # @param id [String] job id
  # @param status_updates [Hash] updated values
  # @param expiration [Integer] optional expire time in seconds
  # @param redis_pool [ConnectionPool] optional redis connection pool
  # @return [String] Redis operation status code
  #
  # source://sidekiq-status//lib/sidekiq-status/storage.rb#14
  def store_for_id(id, status_updates, expiration = T.unsafe(nil), redis_pool = T.unsafe(nil)); end

  # Stores job status and sets expiration time to it
  # only in case of :failed or :stopped job
  #
  # @param id [String] job id
  # @param job [Symbol] status
  # @param expiration [Integer] optional expire time in seconds
  # @param redis_pool [ConnectionPool] optional redis connection pool
  # @return [String] Redis operation status code
  #
  # source://sidekiq-status//lib/sidekiq-status/storage.rb#32
  def store_status(id, status, expiration = T.unsafe(nil), redis_pool = T.unsafe(nil)); end

  private

  # source://sidekiq-status//lib/sidekiq-status/storage.rb#121
  def key(id); end

  # Yields redis connection. Uses redis pool if available.
  #
  # @param redis_pool [ConnectionPool] optional redis connection pool
  #
  # source://sidekiq-status//lib/sidekiq-status/storage.rb#109
  def redis_connection(redis_pool = T.unsafe(nil)); end

  # Searches the jobs Array for the job_id
  #
  # @param scheduled_jobs, [Array] results of Redis schedule key
  # @param id [String] job id
  #
  # source://sidekiq-status//lib/sidekiq-status/storage.rb#100
  def scan_scheduled_jobs_for_jid(scheduled_jobs, job_id); end

  # Gets the batch of scheduled jobs based on input options
  # Uses Redis zrangebyscore for log(n) search, if unix-time is provided
  #
  # @param options, [Hash] options hash containing (REQUIRED) keys:
  #   -  conn: Redis connection
  #   -  start: start score (i.e. -inf or a unix timestamp)
  #   -  end: end score (i.e. +inf or a unix timestamp)
  #   -  offset: current progress through (all) jobs (e.g.: 100 if you want jobs from 100 to BATCH_LIMIT)
  #
  # source://sidekiq-status//lib/sidekiq-status/storage.rb#93
  def schedule_batch(options); end
end

# source://sidekiq-status//lib/sidekiq-status/storage.rb#3
Sidekiq::Status::Storage::BATCH_LIMIT = T.let(T.unsafe(nil), Integer)

# source://sidekiq-status//lib/sidekiq-status/storage.rb#2
Sidekiq::Status::Storage::RESERVED_FIELDS = T.let(T.unsafe(nil), Array)

# source://sidekiq-status//lib/sidekiq-status/version.rb#3
Sidekiq::Status::VERSION = T.let(T.unsafe(nil), String)

# source://sidekiq-status//lib/sidekiq-status/worker.rb#1
module Sidekiq::Status::Worker
  include ::Sidekiq::Status::Storage

  # Sets current task progress
  # (inspired by resque-status)
  #
  # @param Fixnum number of tasks done
  # @param String optional message
  # @return [String]
  #
  # source://sidekiq-status//lib/sidekiq-status/worker.rb#29
  def at(num, message = T.unsafe(nil)); end

  # Returns the value of attribute expiration.
  #
  # source://sidekiq-status//lib/sidekiq-status/worker.rb#7
  def expiration; end

  # Sets the attribute expiration
  #
  # @param value the value to set the attribute expiration to.
  #
  # source://sidekiq-status//lib/sidekiq-status/worker.rb#7
  def expiration=(_arg0); end

  # Read value from job status hash
  #
  # @param String|Symbol hask key
  # @return [String]
  #
  # source://sidekiq-status//lib/sidekiq-status/worker.rb#20
  def retrieve(name); end

  # Stores multiple values into a job's status hash,
  # sets last update time
  #
  # @param status_updates [Hash] updated values
  # @return [String] Redis operation status code
  #
  # source://sidekiq-status//lib/sidekiq-status/worker.rb#13
  def store(hash); end

  # Sets total number of tasks
  #
  # @param Fixnum total number of tasks
  # @return [String]
  #
  # source://sidekiq-status//lib/sidekiq-status/worker.rb#38
  def total(num); end

  private

  # source://sidekiq-status//lib/sidekiq-status/worker.rb#45
  def working_at; end
end

# source://sidekiq-status//lib/sidekiq-status/worker.rb#4
class Sidekiq::Status::Worker::Stopped < ::StandardError; end
