# ==============================================================================
# docker-compose
# ==============================================================================
services:
  # ----------------------------------------------------------------------------
  app: &haguruma-app-base
    # ----------------------------------------------------------------------------
    build:
      context: .
      dockerfile: docker/local.Dockerfile
      args:
        RAILS_ENV: development
    command: bundle exec rails server -b 0.0.0.0 -p '3000'
    ports:
      - '3000:3000'
    links:
      - postgres
      - redis
    env_file:
      - .env.local
      - secrets.env
    environment:
      LANG: 'C.UTF-8'
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
      RUBYOPT: '-W:no-deprecated -W:no-experimental'
      RUBOCOP_CACHE_ROOT: 'tmp/rubocop_cache'
      VITE_RUBY_HOST: vite-dev-server
    volumes:
      - .:/rails_app
      - bundle-data:/usr/local/bundle
    stdin_open: true
    tty: true

  # ----------------------------------------------------------------------------
  vite-dev-server:
    # ----------------------------------------------------------------------------
    <<: *haguruma-app-base
    build:
      context: .
      dockerfile: docker/local.Dockerfile
      args:
        RAILS_ENV: development
    command: ./bin/vite dev
    environment:
      VITE_RUBY_HOST: '0.0.0.0'
    ports:
      - '3036:3036'

  # ----------------------------------------------------------------------------
  worker:
    # ----------------------------------------------------------------------------
    <<: *haguruma-app-base
    build:
      context: .
      dockerfile: docker/local.Dockerfile
      args:
        RAILS_ENV: development
    ports: []
    command: bundle exec sidekiq

  # ----------------------------------------------------------------------------
  postgres:
    # ----------------------------------------------------------------------------
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # ----------------------------------------------------------------------------
  redis:
    # ----------------------------------------------------------------------------
    image: redis:7-alpine
    ports:
      - '6379:6379'
    command: [redis-server, --loglevel, notice]
    volumes:
      - redis-data:/data

# ----------------------------------------------------------------------------
volumes:
  # ----------------------------------------------------------------------------
  bundle-data: {}
  postgres-data: {}
  redis-data: {}
