# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Eventbridge::ProcessWorker`.
# Please instead update this file by running `bin/tapioca dsl Eventbridge::ProcessWorker`.


class Eventbridge::ProcessWorker
  class << self
    sig { params(message_json: ::String).returns(String) }
    def perform_async(message_json); end

    sig do
      params(
        interval: T.any(DateTime, Time, ActiveSupport::TimeWithZone),
        message_json: ::String
      ).returns(String)
    end
    def perform_at(interval, message_json); end

    sig { params(interval: T.any(Numeric, ActiveSupport::Duration), message_json: ::String).returns(String) }
    def perform_in(interval, message_json); end
  end
end
