#!/usr/bin/env bash
set -euo pipefail

# Usage: update-mr-description.sh <checklist-file>
# Updates the GitLab MR description (main -> deploy-production) with the checklist content.

CHECKLIST_FILE="${1:?Usage: update-mr-description.sh <checklist-file>}"

if [ ! -f "$CHECKLIST_FILE" ]; then
  echo "ERROR: Checklist file not found: $CHECKLIST_FILE"
  exit 1
fi

: "${GITLAB_API_ENDPOINT:?GITLAB_API_ENDPOINT is required}"
: "${GITLAB_API_PRIVATE_TOKEN:?GITLAB_API_PRIVATE_TOKEN is required}"
: "${CI_PROJECT_ID:?CI_PROJECT_ID is required}"
: "${CI_MERGE_REQUEST_IID:?CI_MERGE_REQUEST_IID is required}"

MR_IID="$CI_MERGE_REQUEST_IID"

echo "Found MR !${MR_IID}, updating description..."

# Build description with metadata
CHECKLIST_CONTENT=$(cat "$CHECKLIST_FILE")
TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M:%S UTC')

DESCRIPTION=$(cat <<EOF
${CHECKLIST_CONTENT}

---

_Generated by CI pipeline at ${TIMESTAMP}_
_Commit: ${CI_COMMIT_SHA:-unknown} | Pipeline: #${CI_PIPELINE_ID:-unknown}_
EOF
)

# JSON-escape the description and update MR
PAYLOAD=$(jq -n --arg desc "$DESCRIPTION" '{ description: $desc }')

HTTP_STATUS=$(curl -s -o /tmp/mr_response.json -w '%{http_code}' \
  --request PUT \
  --header "PRIVATE-TOKEN: $GITLAB_API_PRIVATE_TOKEN" \
  --header "Content-Type: application/json" \
  --data "$PAYLOAD" \
  "${GITLAB_API_ENDPOINT}/projects/${CI_PROJECT_ID}/merge_requests/${MR_IID}")

if [ "$HTTP_STATUS" -ge 200 ] && [ "$HTTP_STATUS" -lt 300 ]; then
  echo "Successfully updated MR !${MR_IID} description."
else
  echo "ERROR: Failed to update MR. HTTP status: $HTTP_STATUS"
  cat /tmp/mr_response.json
  exit 1
fi
