# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `TenantTheme`.
# Please instead update this file by running `bin/tapioca dsl TenantTheme`.


class TenantTheme
  include GeneratedAssociationMethods
  include GeneratedAttributeMethods
  extend CommonRelationMethods
  extend GeneratedRelationMethods

  private

  sig { returns(NilClass) }
  def to_ary; end

  class << self
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::TenantTheme).void)
      ).returns(::TenantTheme)
    end
    def new(attributes = nil, &block); end
  end

  module CommonRelationMethods
    sig { params(block: T.nilable(T.proc.params(record: ::TenantTheme).returns(T.untyped))).returns(T::Boolean) }
    def any?(&block); end

    sig { params(column_name: T.any(String, Symbol)).returns(T.any(Integer, Float, BigDecimal)) }
    def average(column_name); end

    sig { params(block: T.nilable(T.proc.params(object: ::TenantTheme).void)).returns(::TenantTheme) }
    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::TenantTheme).void)
      ).returns(T::Array[::TenantTheme])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::TenantTheme).void)
      ).returns(::TenantTheme)
    end
    def build(attributes = nil, &block); end

    sig { params(operation: Symbol, column_name: T.any(String, Symbol)).returns(T.any(Integer, Float, BigDecimal)) }
    def calculate(operation, column_name); end

    sig { params(column_name: T.nilable(T.any(String, Symbol))).returns(Integer) }
    sig { params(column_name: NilClass, block: T.proc.params(object: ::TenantTheme).void).returns(Integer) }
    def count(column_name = nil, &block); end

    sig { params(block: T.nilable(T.proc.params(object: ::TenantTheme).void)).returns(::TenantTheme) }
    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::TenantTheme).void)
      ).returns(T::Array[::TenantTheme])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::TenantTheme).void)
      ).returns(::TenantTheme)
    end
    def create(attributes = nil, &block); end

    sig { params(block: T.nilable(T.proc.params(object: ::TenantTheme).void)).returns(::TenantTheme) }
    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::TenantTheme).void)
      ).returns(T::Array[::TenantTheme])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::TenantTheme).void)
      ).returns(::TenantTheme)
    end
    def create!(attributes = nil, &block); end

    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::TenantTheme).void)
      ).returns(T::Array[::TenantTheme])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::TenantTheme).void)
      ).returns(::TenantTheme)
    end
    def create_or_find_by(attributes, &block); end

    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::TenantTheme).void)
      ).returns(T::Array[::TenantTheme])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::TenantTheme).void)
      ).returns(::TenantTheme)
    end
    def create_or_find_by!(attributes, &block); end

    sig { returns(T::Array[::TenantTheme]) }
    def destroy_all; end

    sig { params(conditions: T.untyped).returns(T::Boolean) }
    def exists?(conditions = :none); end

    sig { returns(T.nilable(::TenantTheme)) }
    def fifth; end

    sig { returns(::TenantTheme) }
    def fifth!; end

    sig do
      params(
        args: T.any(String, Symbol, ::ActiveSupport::Multibyte::Chars, T::Boolean, BigDecimal, Numeric, ::ActiveRecord::Type::Binary::Data, ::ActiveRecord::Type::Time::Value, Date, Time, ::ActiveSupport::Duration, T::Class[T.anything])
      ).returns(::TenantTheme)
    end
    sig do
      params(
        args: T::Array[T.any(String, Symbol, ::ActiveSupport::Multibyte::Chars, T::Boolean, BigDecimal, Numeric, ::ActiveRecord::Type::Binary::Data, ::ActiveRecord::Type::Time::Value, Date, Time, ::ActiveSupport::Duration, T::Class[T.anything])]
      ).returns(T::Enumerable[::TenantTheme])
    end
    sig { params(args: NilClass, block: T.proc.params(object: ::TenantTheme).void).returns(T.nilable(::TenantTheme)) }
    def find(args = nil, &block); end

    sig { params(args: T.untyped).returns(T.nilable(::TenantTheme)) }
    def find_by(*args); end

    sig { params(args: T.untyped).returns(::TenantTheme) }
    def find_by!(*args); end

    sig do
      params(
        start: T.untyped,
        finish: T.untyped,
        batch_size: Integer,
        error_on_ignore: T.untyped,
        cursor: T.untyped,
        order: Symbol,
        block: T.proc.params(object: ::TenantTheme).void
      ).void
    end
    sig do
      params(
        start: T.untyped,
        finish: T.untyped,
        batch_size: Integer,
        error_on_ignore: T.untyped,
        cursor: T.untyped,
        order: Symbol
      ).returns(T::Enumerator[::TenantTheme])
    end
    def find_each(start: nil, finish: nil, batch_size: 1000, error_on_ignore: nil, cursor: primary_key, order: :asc, &block); end

    sig do
      params(
        start: T.untyped,
        finish: T.untyped,
        batch_size: Integer,
        error_on_ignore: T.untyped,
        cursor: T.untyped,
        order: Symbol,
        block: T.proc.params(object: T::Array[::TenantTheme]).void
      ).void
    end
    sig do
      params(
        start: T.untyped,
        finish: T.untyped,
        batch_size: Integer,
        error_on_ignore: T.untyped,
        cursor: T.untyped,
        order: Symbol
      ).returns(T::Enumerator[T::Enumerator[::TenantTheme]])
    end
    def find_in_batches(start: nil, finish: nil, batch_size: 1000, error_on_ignore: nil, cursor: primary_key, order: :asc, &block); end

    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::TenantTheme).void)
      ).returns(T::Array[::TenantTheme])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::TenantTheme).void)
      ).returns(::TenantTheme)
    end
    def find_or_create_by(attributes, &block); end

    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::TenantTheme).void)
      ).returns(T::Array[::TenantTheme])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::TenantTheme).void)
      ).returns(::TenantTheme)
    end
    def find_or_create_by!(attributes, &block); end

    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::TenantTheme).void)
      ).returns(T::Array[::TenantTheme])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::TenantTheme).void)
      ).returns(::TenantTheme)
    end
    def find_or_initialize_by(attributes, &block); end

    sig { params(signed_id: T.untyped, purpose: T.untyped).returns(T.nilable(::TenantTheme)) }
    def find_signed(signed_id, purpose: nil); end

    sig { params(signed_id: T.untyped, purpose: T.untyped).returns(::TenantTheme) }
    def find_signed!(signed_id, purpose: nil); end

    sig { params(arg: T.untyped, args: T.untyped).returns(::TenantTheme) }
    def find_sole_by(arg, *args); end

    sig { returns(T.nilable(::TenantTheme)) }
    sig { params(limit: Integer).returns(T::Array[::TenantTheme]) }
    def first(limit = nil); end

    sig { returns(::TenantTheme) }
    def first!; end

    sig { returns(T.nilable(::TenantTheme)) }
    def forty_two; end

    sig { returns(::TenantTheme) }
    def forty_two!; end

    sig { returns(T.nilable(::TenantTheme)) }
    def fourth; end

    sig { returns(::TenantTheme) }
    def fourth!; end

    sig { returns(T::Array[T.untyped]) }
    def ids; end

    sig do
      params(
        of: Integer,
        start: T.untyped,
        finish: T.untyped,
        load: T.untyped,
        error_on_ignore: T.untyped,
        cursor: T.untyped,
        order: Symbol,
        use_ranges: T.untyped,
        block: T.proc.params(object: PrivateRelation).void
      ).void
    end
    sig do
      params(
        of: Integer,
        start: T.untyped,
        finish: T.untyped,
        load: T.untyped,
        error_on_ignore: T.untyped,
        cursor: T.untyped,
        order: Symbol,
        use_ranges: T.untyped
      ).returns(::ActiveRecord::Batches::BatchEnumerator)
    end
    def in_batches(of: 1000, start: nil, finish: nil, load: false, error_on_ignore: nil, cursor: primary_key, order: :asc, use_ranges: nil, &block); end

    sig { params(record: T.untyped).returns(T::Boolean) }
    def include?(record); end

    sig { returns(T.nilable(::TenantTheme)) }
    sig { params(limit: Integer).returns(T::Array[::TenantTheme]) }
    def last(limit = nil); end

    sig { returns(::TenantTheme) }
    def last!; end

    sig { params(block: T.nilable(T.proc.params(record: ::TenantTheme).returns(T.untyped))).returns(T::Boolean) }
    def many?(&block); end

    sig { params(column_name: T.any(String, Symbol)).returns(T.untyped) }
    def maximum(column_name); end

    sig { params(record: T.untyped).returns(T::Boolean) }
    def member?(record); end

    sig { params(column_name: T.any(String, Symbol)).returns(T.untyped) }
    def minimum(column_name); end

    sig { params(block: T.nilable(T.proc.params(object: ::TenantTheme).void)).returns(::TenantTheme) }
    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::TenantTheme).void)
      ).returns(T::Array[::TenantTheme])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::TenantTheme).void)
      ).returns(::TenantTheme)
    end
    def new(attributes = nil, &block); end

    sig { params(block: T.nilable(T.proc.params(record: ::TenantTheme).returns(T.untyped))).returns(T::Boolean) }
    def none?(&block); end

    sig { params(block: T.nilable(T.proc.params(record: ::TenantTheme).returns(T.untyped))).returns(T::Boolean) }
    def one?(&block); end

    sig { params(column_names: T.untyped).returns(T.untyped) }
    def pick(*column_names); end

    sig { params(column_names: T.untyped).returns(T.untyped) }
    def pluck(*column_names); end

    sig { returns(T.nilable(::TenantTheme)) }
    def second; end

    sig { returns(::TenantTheme) }
    def second!; end

    sig { returns(T.nilable(::TenantTheme)) }
    def second_to_last; end

    sig { returns(::TenantTheme) }
    def second_to_last!; end

    sig { returns(::TenantTheme) }
    def sole; end

    sig { params(initial_value_or_column: T.untyped).returns(T.any(Integer, Float, BigDecimal)) }
    sig do
      type_parameters(:U)
        .params(
          initial_value_or_column: T.nilable(T.type_parameter(:U)),
          block: T.proc.params(object: ::TenantTheme).returns(T.type_parameter(:U))
        ).returns(T.type_parameter(:U))
    end
    def sum(initial_value_or_column = nil, &block); end

    sig { returns(T.nilable(::TenantTheme)) }
    sig { params(limit: Integer).returns(T::Array[::TenantTheme]) }
    def take(limit = nil); end

    sig { returns(::TenantTheme) }
    def take!; end

    sig { returns(T.nilable(::TenantTheme)) }
    def third; end

    sig { returns(::TenantTheme) }
    def third!; end

    sig { returns(T.nilable(::TenantTheme)) }
    def third_to_last; end

    sig { returns(::TenantTheme) }
    def third_to_last!; end
  end

  module GeneratedAssociationMethods
    sig { params(args: T.untyped, blk: T.untyped).returns(::Tenant) }
    def build_tenant(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::Tenant) }
    def create_tenant(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::Tenant) }
    def create_tenant!(*args, &blk); end

    sig { returns(T.nilable(::Tenant)) }
    def reload_tenant; end

    sig { void }
    def reset_tenant; end

    sig { returns(T.nilable(::Tenant)) }
    def tenant; end

    sig { params(value: T.nilable(::Tenant)).void }
    def tenant=(value); end

    sig { returns(T::Boolean) }
    def tenant_changed?; end

    sig { returns(T::Boolean) }
    def tenant_previously_changed?; end
  end

  module GeneratedAssociationRelationMethods
    sig { returns(PrivateAssociationRelation) }
    def all; end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def and(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def annotate(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def arel_columns(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def create_with(*args, &blk); end

    sig { params(value: T::Boolean).returns(PrivateAssociationRelation) }
    def distinct(value = true); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def eager_load(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def except(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def excluding(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def extending(*args, &blk); end

    sig { params(association: Symbol).returns(T::Array[T.untyped]) }
    def extract_associated(association); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def from(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelationGroupChain) }
    def group(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def having(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def in_order_of(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def includes(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def invert_where(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def left_joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def left_outer_joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def limit(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def lock(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def merge(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def none(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def null_relation?(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def offset(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def only(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def optimizer_hints(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def or(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def order(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def preload(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def readonly(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def references(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def regroup(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def reorder(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def reselect(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def reverse_order(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def rewhere(*args, &blk); end

    sig { params(args: T.untyped).returns(PrivateAssociationRelation) }
    sig { params(blk: T.proc.params(record: ::TenantTheme).returns(BasicObject)).returns(T::Array[::TenantTheme]) }
    def select(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def strict_loading(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def structurally_compatible?(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def uniq!(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def unscope(*args, &blk); end

    sig { returns(PrivateAssociationRelationWhereChain) }
    sig { params(args: T.untyped).returns(PrivateAssociationRelation) }
    def where(*args); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def with(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def with_recursive(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def without(*args, &blk); end
  end

  module GeneratedAttributeMethods
    sig { returns(::String) }
    def border_color; end

    sig { params(value: ::String).returns(::String) }
    def border_color=(value); end

    sig { returns(T::Boolean) }
    def border_color?; end

    sig { returns(T.nilable(::String)) }
    def border_color_before_last_save; end

    sig { returns(T.untyped) }
    def border_color_before_type_cast; end

    sig { returns(T::Boolean) }
    def border_color_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def border_color_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def border_color_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def border_color_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def border_color_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def border_color_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def border_color_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def border_color_previously_was; end

    sig { returns(T.nilable(::String)) }
    def border_color_was; end

    sig { void }
    def border_color_will_change!; end

    sig { returns(::String) }
    def button_font_family; end

    sig { params(value: ::String).returns(::String) }
    def button_font_family=(value); end

    sig { returns(T::Boolean) }
    def button_font_family?; end

    sig { returns(T.nilable(::String)) }
    def button_font_family_before_last_save; end

    sig { returns(T.untyped) }
    def button_font_family_before_type_cast; end

    sig { returns(T::Boolean) }
    def button_font_family_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def button_font_family_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def button_font_family_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def button_font_family_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def button_font_family_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def button_font_family_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def button_font_family_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def button_font_family_previously_was; end

    sig { returns(T.nilable(::String)) }
    def button_font_family_was; end

    sig { void }
    def button_font_family_will_change!; end

    sig { returns(::String) }
    def button_primary_background_color; end

    sig { params(value: ::String).returns(::String) }
    def button_primary_background_color=(value); end

    sig { returns(T::Boolean) }
    def button_primary_background_color?; end

    sig { returns(T.nilable(::String)) }
    def button_primary_background_color_before_last_save; end

    sig { returns(T.untyped) }
    def button_primary_background_color_before_type_cast; end

    sig { returns(T::Boolean) }
    def button_primary_background_color_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def button_primary_background_color_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def button_primary_background_color_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def button_primary_background_color_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def button_primary_background_color_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def button_primary_background_color_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def button_primary_background_color_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def button_primary_background_color_previously_was; end

    sig { returns(T.nilable(::String)) }
    def button_primary_background_color_was; end

    sig { void }
    def button_primary_background_color_will_change!; end

    sig { returns(::String) }
    def button_primary_text_color; end

    sig { params(value: ::String).returns(::String) }
    def button_primary_text_color=(value); end

    sig { returns(T::Boolean) }
    def button_primary_text_color?; end

    sig { returns(T.nilable(::String)) }
    def button_primary_text_color_before_last_save; end

    sig { returns(T.untyped) }
    def button_primary_text_color_before_type_cast; end

    sig { returns(T::Boolean) }
    def button_primary_text_color_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def button_primary_text_color_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def button_primary_text_color_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def button_primary_text_color_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def button_primary_text_color_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def button_primary_text_color_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def button_primary_text_color_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def button_primary_text_color_previously_was; end

    sig { returns(T.nilable(::String)) }
    def button_primary_text_color_was; end

    sig { void }
    def button_primary_text_color_will_change!; end

    sig { returns(::String) }
    def button_secondary_background_color; end

    sig { params(value: ::String).returns(::String) }
    def button_secondary_background_color=(value); end

    sig { returns(T::Boolean) }
    def button_secondary_background_color?; end

    sig { returns(T.nilable(::String)) }
    def button_secondary_background_color_before_last_save; end

    sig { returns(T.untyped) }
    def button_secondary_background_color_before_type_cast; end

    sig { returns(T::Boolean) }
    def button_secondary_background_color_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def button_secondary_background_color_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def button_secondary_background_color_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def button_secondary_background_color_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def button_secondary_background_color_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def button_secondary_background_color_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def button_secondary_background_color_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def button_secondary_background_color_previously_was; end

    sig { returns(T.nilable(::String)) }
    def button_secondary_background_color_was; end

    sig { void }
    def button_secondary_background_color_will_change!; end

    sig { returns(::String) }
    def button_secondary_border_color; end

    sig { params(value: ::String).returns(::String) }
    def button_secondary_border_color=(value); end

    sig { returns(T::Boolean) }
    def button_secondary_border_color?; end

    sig { returns(T.nilable(::String)) }
    def button_secondary_border_color_before_last_save; end

    sig { returns(T.untyped) }
    def button_secondary_border_color_before_type_cast; end

    sig { returns(T::Boolean) }
    def button_secondary_border_color_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def button_secondary_border_color_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def button_secondary_border_color_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def button_secondary_border_color_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def button_secondary_border_color_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def button_secondary_border_color_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def button_secondary_border_color_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def button_secondary_border_color_previously_was; end

    sig { returns(T.nilable(::String)) }
    def button_secondary_border_color_was; end

    sig { void }
    def button_secondary_border_color_will_change!; end

    sig { returns(::String) }
    def button_secondary_text_color; end

    sig { params(value: ::String).returns(::String) }
    def button_secondary_text_color=(value); end

    sig { returns(T::Boolean) }
    def button_secondary_text_color?; end

    sig { returns(T.nilable(::String)) }
    def button_secondary_text_color_before_last_save; end

    sig { returns(T.untyped) }
    def button_secondary_text_color_before_type_cast; end

    sig { returns(T::Boolean) }
    def button_secondary_text_color_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def button_secondary_text_color_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def button_secondary_text_color_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def button_secondary_text_color_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def button_secondary_text_color_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def button_secondary_text_color_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def button_secondary_text_color_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def button_secondary_text_color_previously_was; end

    sig { returns(T.nilable(::String)) }
    def button_secondary_text_color_was; end

    sig { void }
    def button_secondary_text_color_will_change!; end

    sig { returns(::String) }
    def caption_font_family; end

    sig { params(value: ::String).returns(::String) }
    def caption_font_family=(value); end

    sig { returns(T::Boolean) }
    def caption_font_family?; end

    sig { returns(T.nilable(::String)) }
    def caption_font_family_before_last_save; end

    sig { returns(T.untyped) }
    def caption_font_family_before_type_cast; end

    sig { returns(T::Boolean) }
    def caption_font_family_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def caption_font_family_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def caption_font_family_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def caption_font_family_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def caption_font_family_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def caption_font_family_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def caption_font_family_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def caption_font_family_previously_was; end

    sig { returns(T.nilable(::String)) }
    def caption_font_family_was; end

    sig { void }
    def caption_font_family_will_change!; end

    sig { returns(::String) }
    def caption_text_color; end

    sig { params(value: ::String).returns(::String) }
    def caption_text_color=(value); end

    sig { returns(T::Boolean) }
    def caption_text_color?; end

    sig { returns(T.nilable(::String)) }
    def caption_text_color_before_last_save; end

    sig { returns(T.untyped) }
    def caption_text_color_before_type_cast; end

    sig { returns(T::Boolean) }
    def caption_text_color_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def caption_text_color_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def caption_text_color_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def caption_text_color_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def caption_text_color_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def caption_text_color_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def caption_text_color_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def caption_text_color_previously_was; end

    sig { returns(T.nilable(::String)) }
    def caption_text_color_was; end

    sig { void }
    def caption_text_color_will_change!; end

    sig { returns(::ActiveSupport::TimeWithZone) }
    def created_at; end

    sig { params(value: ::ActiveSupport::TimeWithZone).returns(::ActiveSupport::TimeWithZone) }
    def created_at=(value); end

    sig { returns(T::Boolean) }
    def created_at?; end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def created_at_before_last_save; end

    sig { returns(T.untyped) }
    def created_at_before_type_cast; end

    sig { returns(T::Boolean) }
    def created_at_came_from_user?; end

    sig { returns(T.nilable([::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone])) }
    def created_at_change; end

    sig { returns(T.nilable([::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone])) }
    def created_at_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def created_at_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def created_at_in_database; end

    sig { returns(T.nilable([::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone])) }
    def created_at_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def created_at_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def created_at_previously_was; end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def created_at_was; end

    sig { void }
    def created_at_will_change!; end

    sig { returns(::String) }
    def general_font_family; end

    sig { params(value: ::String).returns(::String) }
    def general_font_family=(value); end

    sig { returns(T::Boolean) }
    def general_font_family?; end

    sig { returns(T.nilable(::String)) }
    def general_font_family_before_last_save; end

    sig { returns(T.untyped) }
    def general_font_family_before_type_cast; end

    sig { returns(T::Boolean) }
    def general_font_family_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def general_font_family_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def general_font_family_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def general_font_family_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def general_font_family_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def general_font_family_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def general_font_family_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def general_font_family_previously_was; end

    sig { returns(T.nilable(::String)) }
    def general_font_family_was; end

    sig { void }
    def general_font_family_will_change!; end

    sig { returns(::String) }
    def general_text_color; end

    sig { params(value: ::String).returns(::String) }
    def general_text_color=(value); end

    sig { returns(T::Boolean) }
    def general_text_color?; end

    sig { returns(T.nilable(::String)) }
    def general_text_color_before_last_save; end

    sig { returns(T.untyped) }
    def general_text_color_before_type_cast; end

    sig { returns(T::Boolean) }
    def general_text_color_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def general_text_color_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def general_text_color_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def general_text_color_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def general_text_color_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def general_text_color_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def general_text_color_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def general_text_color_previously_was; end

    sig { returns(T.nilable(::String)) }
    def general_text_color_was; end

    sig { void }
    def general_text_color_will_change!; end

    sig { returns(::String) }
    def id; end

    sig { params(value: ::String).returns(::String) }
    def id=(value); end

    sig { returns(T::Boolean) }
    def id?; end

    sig { returns(T.nilable(::String)) }
    def id_before_last_save; end

    sig { returns(T.untyped) }
    def id_before_type_cast; end

    sig { returns(T::Boolean) }
    def id_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def id_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def id_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def id_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def id_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def id_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def id_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def id_previously_was; end

    sig { returns(::String) }
    def id_value; end

    sig { params(value: ::String).returns(::String) }
    def id_value=(value); end

    sig { returns(T::Boolean) }
    def id_value?; end

    sig { returns(T.nilable(::String)) }
    def id_value_before_last_save; end

    sig { returns(T.untyped) }
    def id_value_before_type_cast; end

    sig { returns(T::Boolean) }
    def id_value_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def id_value_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def id_value_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def id_value_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def id_value_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def id_value_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def id_value_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def id_value_previously_was; end

    sig { returns(T.nilable(::String)) }
    def id_value_was; end

    sig { void }
    def id_value_will_change!; end

    sig { returns(T.nilable(::String)) }
    def id_was; end

    sig { void }
    def id_will_change!; end

    sig { returns(::String) }
    def label_background_color; end

    sig { params(value: ::String).returns(::String) }
    def label_background_color=(value); end

    sig { returns(T::Boolean) }
    def label_background_color?; end

    sig { returns(T.nilable(::String)) }
    def label_background_color_before_last_save; end

    sig { returns(T.untyped) }
    def label_background_color_before_type_cast; end

    sig { returns(T::Boolean) }
    def label_background_color_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def label_background_color_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def label_background_color_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def label_background_color_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def label_background_color_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def label_background_color_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def label_background_color_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def label_background_color_previously_was; end

    sig { returns(T.nilable(::String)) }
    def label_background_color_was; end

    sig { void }
    def label_background_color_will_change!; end

    sig { returns(::String) }
    def label_font_family; end

    sig { params(value: ::String).returns(::String) }
    def label_font_family=(value); end

    sig { returns(T::Boolean) }
    def label_font_family?; end

    sig { returns(T.nilable(::String)) }
    def label_font_family_before_last_save; end

    sig { returns(T.untyped) }
    def label_font_family_before_type_cast; end

    sig { returns(T::Boolean) }
    def label_font_family_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def label_font_family_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def label_font_family_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def label_font_family_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def label_font_family_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def label_font_family_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def label_font_family_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def label_font_family_previously_was; end

    sig { returns(T.nilable(::String)) }
    def label_font_family_was; end

    sig { void }
    def label_font_family_will_change!; end

    sig { returns(::String) }
    def label_text_color; end

    sig { params(value: ::String).returns(::String) }
    def label_text_color=(value); end

    sig { returns(T::Boolean) }
    def label_text_color?; end

    sig { returns(T.nilable(::String)) }
    def label_text_color_before_last_save; end

    sig { returns(T.untyped) }
    def label_text_color_before_type_cast; end

    sig { returns(T::Boolean) }
    def label_text_color_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def label_text_color_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def label_text_color_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def label_text_color_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def label_text_color_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def label_text_color_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def label_text_color_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def label_text_color_previously_was; end

    sig { returns(T.nilable(::String)) }
    def label_text_color_was; end

    sig { void }
    def label_text_color_will_change!; end

    sig { returns(::String) }
    def link_text_color; end

    sig { params(value: ::String).returns(::String) }
    def link_text_color=(value); end

    sig { returns(T::Boolean) }
    def link_text_color?; end

    sig { returns(T.nilable(::String)) }
    def link_text_color_before_last_save; end

    sig { returns(T.untyped) }
    def link_text_color_before_type_cast; end

    sig { returns(T::Boolean) }
    def link_text_color_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def link_text_color_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def link_text_color_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def link_text_color_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def link_text_color_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def link_text_color_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def link_text_color_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def link_text_color_previously_was; end

    sig { returns(T.nilable(::String)) }
    def link_text_color_was; end

    sig { void }
    def link_text_color_will_change!; end

    sig { returns(T::Boolean) }
    def link_underline; end

    sig { params(value: T::Boolean).returns(T::Boolean) }
    def link_underline=(value); end

    sig { returns(T::Boolean) }
    def link_underline?; end

    sig { returns(T.nilable(T::Boolean)) }
    def link_underline_before_last_save; end

    sig { returns(T.untyped) }
    def link_underline_before_type_cast; end

    sig { returns(T::Boolean) }
    def link_underline_came_from_user?; end

    sig { returns(T.nilable([T::Boolean, T::Boolean])) }
    def link_underline_change; end

    sig { returns(T.nilable([T::Boolean, T::Boolean])) }
    def link_underline_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def link_underline_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(T::Boolean)) }
    def link_underline_in_database; end

    sig { returns(T.nilable([T::Boolean, T::Boolean])) }
    def link_underline_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def link_underline_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(T::Boolean)) }
    def link_underline_previously_was; end

    sig { returns(T.nilable(T::Boolean)) }
    def link_underline_was; end

    sig { void }
    def link_underline_will_change!; end

    sig { returns(::String) }
    def navigation_font_family; end

    sig { params(value: ::String).returns(::String) }
    def navigation_font_family=(value); end

    sig { returns(T::Boolean) }
    def navigation_font_family?; end

    sig { returns(T.nilable(::String)) }
    def navigation_font_family_before_last_save; end

    sig { returns(T.untyped) }
    def navigation_font_family_before_type_cast; end

    sig { returns(T::Boolean) }
    def navigation_font_family_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def navigation_font_family_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def navigation_font_family_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def navigation_font_family_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def navigation_font_family_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def navigation_font_family_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def navigation_font_family_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def navigation_font_family_previously_was; end

    sig { returns(T.nilable(::String)) }
    def navigation_font_family_was; end

    sig { void }
    def navigation_font_family_will_change!; end

    sig { returns(::String) }
    def navigation_text_color; end

    sig { params(value: ::String).returns(::String) }
    def navigation_text_color=(value); end

    sig { returns(T::Boolean) }
    def navigation_text_color?; end

    sig { returns(T.nilable(::String)) }
    def navigation_text_color_before_last_save; end

    sig { returns(T.untyped) }
    def navigation_text_color_before_type_cast; end

    sig { returns(T::Boolean) }
    def navigation_text_color_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def navigation_text_color_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def navigation_text_color_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def navigation_text_color_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def navigation_text_color_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def navigation_text_color_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def navigation_text_color_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def navigation_text_color_previously_was; end

    sig { returns(T.nilable(::String)) }
    def navigation_text_color_was; end

    sig { void }
    def navigation_text_color_will_change!; end

    sig { returns(::String) }
    def page_background_color; end

    sig { params(value: ::String).returns(::String) }
    def page_background_color=(value); end

    sig { returns(T::Boolean) }
    def page_background_color?; end

    sig { returns(T.nilable(::String)) }
    def page_background_color_before_last_save; end

    sig { returns(T.untyped) }
    def page_background_color_before_type_cast; end

    sig { returns(T::Boolean) }
    def page_background_color_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def page_background_color_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def page_background_color_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def page_background_color_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def page_background_color_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def page_background_color_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def page_background_color_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def page_background_color_previously_was; end

    sig { returns(T.nilable(::String)) }
    def page_background_color_was; end

    sig { void }
    def page_background_color_will_change!; end

    sig { void }
    def restore_border_color!; end

    sig { void }
    def restore_button_font_family!; end

    sig { void }
    def restore_button_primary_background_color!; end

    sig { void }
    def restore_button_primary_text_color!; end

    sig { void }
    def restore_button_secondary_background_color!; end

    sig { void }
    def restore_button_secondary_border_color!; end

    sig { void }
    def restore_button_secondary_text_color!; end

    sig { void }
    def restore_caption_font_family!; end

    sig { void }
    def restore_caption_text_color!; end

    sig { void }
    def restore_created_at!; end

    sig { void }
    def restore_general_font_family!; end

    sig { void }
    def restore_general_text_color!; end

    sig { void }
    def restore_id!; end

    sig { void }
    def restore_id_value!; end

    sig { void }
    def restore_label_background_color!; end

    sig { void }
    def restore_label_font_family!; end

    sig { void }
    def restore_label_text_color!; end

    sig { void }
    def restore_link_text_color!; end

    sig { void }
    def restore_link_underline!; end

    sig { void }
    def restore_navigation_font_family!; end

    sig { void }
    def restore_navigation_text_color!; end

    sig { void }
    def restore_page_background_color!; end

    sig { void }
    def restore_tab_active_text_color!; end

    sig { void }
    def restore_tab_active_underline_color!; end

    sig { void }
    def restore_tab_font_family!; end

    sig { void }
    def restore_tab_inactive_text_color!; end

    sig { void }
    def restore_tab_inactive_underline_color!; end

    sig { void }
    def restore_tenant_id!; end

    sig { void }
    def restore_title_font_family!; end

    sig { void }
    def restore_title_text_color!; end

    sig { void }
    def restore_updated_at!; end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_border_color; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_border_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_button_font_family; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_button_font_family?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_button_primary_background_color; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_button_primary_background_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_button_primary_text_color; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_button_primary_text_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_button_secondary_background_color; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_button_secondary_background_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_button_secondary_border_color; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_button_secondary_border_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_button_secondary_text_color; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_button_secondary_text_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_caption_font_family; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_caption_font_family?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_caption_text_color; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_caption_text_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone])) }
    def saved_change_to_created_at; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_created_at?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_general_font_family; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_general_font_family?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_general_text_color; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_general_text_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_id; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_id?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_id_value; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_id_value?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_label_background_color; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_label_background_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_label_font_family; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_label_font_family?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_label_text_color; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_label_text_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_link_text_color; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_link_text_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([T::Boolean, T::Boolean])) }
    def saved_change_to_link_underline; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_link_underline?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_navigation_font_family; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_navigation_font_family?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_navigation_text_color; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_navigation_text_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_page_background_color; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_page_background_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_tab_active_text_color; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_tab_active_text_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_tab_active_underline_color; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_tab_active_underline_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_tab_font_family; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_tab_font_family?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_tab_inactive_text_color; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_tab_inactive_text_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_tab_inactive_underline_color; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_tab_inactive_underline_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_tenant_id; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_tenant_id?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_title_font_family; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_title_font_family?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_title_text_color; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_title_text_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone])) }
    def saved_change_to_updated_at; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_updated_at?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(::String) }
    def tab_active_text_color; end

    sig { params(value: ::String).returns(::String) }
    def tab_active_text_color=(value); end

    sig { returns(T::Boolean) }
    def tab_active_text_color?; end

    sig { returns(T.nilable(::String)) }
    def tab_active_text_color_before_last_save; end

    sig { returns(T.untyped) }
    def tab_active_text_color_before_type_cast; end

    sig { returns(T::Boolean) }
    def tab_active_text_color_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def tab_active_text_color_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def tab_active_text_color_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def tab_active_text_color_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def tab_active_text_color_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def tab_active_text_color_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def tab_active_text_color_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def tab_active_text_color_previously_was; end

    sig { returns(T.nilable(::String)) }
    def tab_active_text_color_was; end

    sig { void }
    def tab_active_text_color_will_change!; end

    sig { returns(::String) }
    def tab_active_underline_color; end

    sig { params(value: ::String).returns(::String) }
    def tab_active_underline_color=(value); end

    sig { returns(T::Boolean) }
    def tab_active_underline_color?; end

    sig { returns(T.nilable(::String)) }
    def tab_active_underline_color_before_last_save; end

    sig { returns(T.untyped) }
    def tab_active_underline_color_before_type_cast; end

    sig { returns(T::Boolean) }
    def tab_active_underline_color_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def tab_active_underline_color_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def tab_active_underline_color_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def tab_active_underline_color_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def tab_active_underline_color_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def tab_active_underline_color_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def tab_active_underline_color_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def tab_active_underline_color_previously_was; end

    sig { returns(T.nilable(::String)) }
    def tab_active_underline_color_was; end

    sig { void }
    def tab_active_underline_color_will_change!; end

    sig { returns(::String) }
    def tab_font_family; end

    sig { params(value: ::String).returns(::String) }
    def tab_font_family=(value); end

    sig { returns(T::Boolean) }
    def tab_font_family?; end

    sig { returns(T.nilable(::String)) }
    def tab_font_family_before_last_save; end

    sig { returns(T.untyped) }
    def tab_font_family_before_type_cast; end

    sig { returns(T::Boolean) }
    def tab_font_family_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def tab_font_family_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def tab_font_family_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def tab_font_family_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def tab_font_family_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def tab_font_family_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def tab_font_family_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def tab_font_family_previously_was; end

    sig { returns(T.nilable(::String)) }
    def tab_font_family_was; end

    sig { void }
    def tab_font_family_will_change!; end

    sig { returns(::String) }
    def tab_inactive_text_color; end

    sig { params(value: ::String).returns(::String) }
    def tab_inactive_text_color=(value); end

    sig { returns(T::Boolean) }
    def tab_inactive_text_color?; end

    sig { returns(T.nilable(::String)) }
    def tab_inactive_text_color_before_last_save; end

    sig { returns(T.untyped) }
    def tab_inactive_text_color_before_type_cast; end

    sig { returns(T::Boolean) }
    def tab_inactive_text_color_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def tab_inactive_text_color_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def tab_inactive_text_color_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def tab_inactive_text_color_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def tab_inactive_text_color_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def tab_inactive_text_color_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def tab_inactive_text_color_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def tab_inactive_text_color_previously_was; end

    sig { returns(T.nilable(::String)) }
    def tab_inactive_text_color_was; end

    sig { void }
    def tab_inactive_text_color_will_change!; end

    sig { returns(::String) }
    def tab_inactive_underline_color; end

    sig { params(value: ::String).returns(::String) }
    def tab_inactive_underline_color=(value); end

    sig { returns(T::Boolean) }
    def tab_inactive_underline_color?; end

    sig { returns(T.nilable(::String)) }
    def tab_inactive_underline_color_before_last_save; end

    sig { returns(T.untyped) }
    def tab_inactive_underline_color_before_type_cast; end

    sig { returns(T::Boolean) }
    def tab_inactive_underline_color_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def tab_inactive_underline_color_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def tab_inactive_underline_color_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def tab_inactive_underline_color_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def tab_inactive_underline_color_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def tab_inactive_underline_color_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def tab_inactive_underline_color_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def tab_inactive_underline_color_previously_was; end

    sig { returns(T.nilable(::String)) }
    def tab_inactive_underline_color_was; end

    sig { void }
    def tab_inactive_underline_color_will_change!; end

    sig { returns(::String) }
    def tenant_id; end

    sig { params(value: ::String).returns(::String) }
    def tenant_id=(value); end

    sig { returns(T::Boolean) }
    def tenant_id?; end

    sig { returns(T.nilable(::String)) }
    def tenant_id_before_last_save; end

    sig { returns(T.untyped) }
    def tenant_id_before_type_cast; end

    sig { returns(T::Boolean) }
    def tenant_id_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def tenant_id_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def tenant_id_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def tenant_id_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def tenant_id_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def tenant_id_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def tenant_id_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def tenant_id_previously_was; end

    sig { returns(T.nilable(::String)) }
    def tenant_id_was; end

    sig { void }
    def tenant_id_will_change!; end

    sig { returns(::String) }
    def title_font_family; end

    sig { params(value: ::String).returns(::String) }
    def title_font_family=(value); end

    sig { returns(T::Boolean) }
    def title_font_family?; end

    sig { returns(T.nilable(::String)) }
    def title_font_family_before_last_save; end

    sig { returns(T.untyped) }
    def title_font_family_before_type_cast; end

    sig { returns(T::Boolean) }
    def title_font_family_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def title_font_family_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def title_font_family_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def title_font_family_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def title_font_family_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def title_font_family_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def title_font_family_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def title_font_family_previously_was; end

    sig { returns(T.nilable(::String)) }
    def title_font_family_was; end

    sig { void }
    def title_font_family_will_change!; end

    sig { returns(::String) }
    def title_text_color; end

    sig { params(value: ::String).returns(::String) }
    def title_text_color=(value); end

    sig { returns(T::Boolean) }
    def title_text_color?; end

    sig { returns(T.nilable(::String)) }
    def title_text_color_before_last_save; end

    sig { returns(T.untyped) }
    def title_text_color_before_type_cast; end

    sig { returns(T::Boolean) }
    def title_text_color_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def title_text_color_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def title_text_color_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def title_text_color_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def title_text_color_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def title_text_color_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def title_text_color_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def title_text_color_previously_was; end

    sig { returns(T.nilable(::String)) }
    def title_text_color_was; end

    sig { void }
    def title_text_color_will_change!; end

    sig { returns(::ActiveSupport::TimeWithZone) }
    def updated_at; end

    sig { params(value: ::ActiveSupport::TimeWithZone).returns(::ActiveSupport::TimeWithZone) }
    def updated_at=(value); end

    sig { returns(T::Boolean) }
    def updated_at?; end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def updated_at_before_last_save; end

    sig { returns(T.untyped) }
    def updated_at_before_type_cast; end

    sig { returns(T::Boolean) }
    def updated_at_came_from_user?; end

    sig { returns(T.nilable([::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone])) }
    def updated_at_change; end

    sig { returns(T.nilable([::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone])) }
    def updated_at_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def updated_at_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def updated_at_in_database; end

    sig { returns(T.nilable([::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone])) }
    def updated_at_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def updated_at_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def updated_at_previously_was; end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def updated_at_was; end

    sig { void }
    def updated_at_will_change!; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_border_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_button_font_family?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_button_primary_background_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_button_primary_text_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_button_secondary_background_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_button_secondary_border_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_button_secondary_text_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_caption_font_family?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_caption_text_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_created_at?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_general_font_family?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_general_text_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_id?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_id_value?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_label_background_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_label_font_family?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_label_text_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_link_text_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_link_underline?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_navigation_font_family?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_navigation_text_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_page_background_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_tab_active_text_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_tab_active_underline_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_tab_font_family?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_tab_inactive_text_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_tab_inactive_underline_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_tenant_id?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_title_font_family?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_title_text_color?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_updated_at?(from: T.unsafe(nil), to: T.unsafe(nil)); end
  end

  module GeneratedRelationMethods
    sig { returns(PrivateRelation) }
    def all; end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def and(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def annotate(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def arel_columns(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def create_with(*args, &blk); end

    sig { params(value: T::Boolean).returns(PrivateRelation) }
    def distinct(value = true); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def eager_load(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def except(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def excluding(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def extending(*args, &blk); end

    sig { params(association: Symbol).returns(T::Array[T.untyped]) }
    def extract_associated(association); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def from(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelationGroupChain) }
    def group(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def having(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def in_order_of(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def includes(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def invert_where(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def left_joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def left_outer_joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def limit(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def lock(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def merge(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def none(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def null_relation?(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def offset(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def only(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def optimizer_hints(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def or(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def order(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def preload(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def readonly(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def references(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def regroup(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def reorder(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def reselect(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def reverse_order(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def rewhere(*args, &blk); end

    sig { params(args: T.untyped).returns(PrivateRelation) }
    sig { params(blk: T.proc.params(record: ::TenantTheme).returns(BasicObject)).returns(T::Array[::TenantTheme]) }
    def select(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def strict_loading(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def structurally_compatible?(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def uniq!(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def unscope(*args, &blk); end

    sig { returns(PrivateRelationWhereChain) }
    sig { params(args: T.untyped).returns(PrivateRelation) }
    def where(*args); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def with(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def with_recursive(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def without(*args, &blk); end
  end

  class PrivateAssociationRelation < ::ActiveRecord::AssociationRelation
    include CommonRelationMethods
    include GeneratedAssociationRelationMethods

    Elem = type_member { { fixed: ::TenantTheme } }

    sig { returns(T::Array[::TenantTheme]) }
    def to_a; end

    sig { returns(T::Array[::TenantTheme]) }
    def to_ary; end
  end

  class PrivateAssociationRelationGroupChain < PrivateAssociationRelation
    Elem = type_member { { fixed: ::TenantTheme } }

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)]) }
    def average(column_name); end

    sig do
      params(
        operation: Symbol,
        column_name: T.any(String, Symbol)
      ).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)])
    end
    def calculate(operation, column_name); end

    sig { params(column_name: T.untyped).returns(T::Hash[T.untyped, Integer]) }
    def count(column_name = nil); end

    sig { params(args: T.untyped, blk: T.untyped).returns(T.self_type) }
    def having(*args, &blk); end

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.untyped]) }
    def maximum(column_name); end

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.untyped]) }
    def minimum(column_name); end

    sig { returns(T::Hash[T.untyped, Integer]) }
    def size; end

    sig do
      params(
        column_name: T.nilable(T.any(String, Symbol)),
        block: T.nilable(T.proc.params(record: T.untyped).returns(T.untyped))
      ).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)])
    end
    def sum(column_name = nil, &block); end
  end

  class PrivateAssociationRelationWhereChain
    Elem = type_member { { fixed: ::TenantTheme } }

    sig { params(args: T.untyped).returns(PrivateAssociationRelation) }
    def associated(*args); end

    sig { params(args: T.untyped).returns(PrivateAssociationRelation) }
    def missing(*args); end

    sig { params(opts: T.untyped, rest: T.untyped).returns(PrivateAssociationRelation) }
    def not(opts, *rest); end
  end

  class PrivateCollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include CommonRelationMethods
    include GeneratedAssociationRelationMethods

    Elem = type_member { { fixed: ::TenantTheme } }

    sig do
      params(
        records: T.any(::TenantTheme, T::Enumerable[T.any(::TenantTheme, T::Enumerable[::TenantTheme])])
      ).returns(PrivateCollectionProxy)
    end
    def <<(*records); end

    sig do
      params(
        records: T.any(::TenantTheme, T::Enumerable[T.any(::TenantTheme, T::Enumerable[::TenantTheme])])
      ).returns(PrivateCollectionProxy)
    end
    def append(*records); end

    sig { returns(PrivateCollectionProxy) }
    def clear; end

    sig do
      params(
        records: T.any(::TenantTheme, T::Enumerable[T.any(::TenantTheme, T::Enumerable[::TenantTheme])])
      ).returns(PrivateCollectionProxy)
    end
    def concat(*records); end

    sig { returns(T::Array[::TenantTheme]) }
    def load_target; end

    sig do
      params(
        records: T.any(::TenantTheme, T::Enumerable[T.any(::TenantTheme, T::Enumerable[::TenantTheme])])
      ).returns(PrivateCollectionProxy)
    end
    def prepend(*records); end

    sig do
      params(
        records: T.any(::TenantTheme, T::Enumerable[T.any(::TenantTheme, T::Enumerable[::TenantTheme])])
      ).returns(PrivateCollectionProxy)
    end
    def push(*records); end

    sig do
      params(
        other_array: T.any(::TenantTheme, T::Enumerable[T.any(::TenantTheme, T::Enumerable[::TenantTheme])])
      ).returns(T::Array[::TenantTheme])
    end
    def replace(other_array); end

    sig { returns(PrivateAssociationRelation) }
    def scope; end

    sig { returns(T::Array[::TenantTheme]) }
    def target; end

    sig { returns(T::Array[::TenantTheme]) }
    def to_a; end

    sig { returns(T::Array[::TenantTheme]) }
    def to_ary; end
  end

  class PrivateRelation < ::ActiveRecord::Relation
    include CommonRelationMethods
    include GeneratedRelationMethods

    Elem = type_member { { fixed: ::TenantTheme } }

    sig { returns(T::Array[::TenantTheme]) }
    def to_a; end

    sig { returns(T::Array[::TenantTheme]) }
    def to_ary; end
  end

  class PrivateRelationGroupChain < PrivateRelation
    Elem = type_member { { fixed: ::TenantTheme } }

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)]) }
    def average(column_name); end

    sig do
      params(
        operation: Symbol,
        column_name: T.any(String, Symbol)
      ).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)])
    end
    def calculate(operation, column_name); end

    sig { params(column_name: T.untyped).returns(T::Hash[T.untyped, Integer]) }
    def count(column_name = nil); end

    sig { params(args: T.untyped, blk: T.untyped).returns(T.self_type) }
    def having(*args, &blk); end

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.untyped]) }
    def maximum(column_name); end

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.untyped]) }
    def minimum(column_name); end

    sig { returns(T::Hash[T.untyped, Integer]) }
    def size; end

    sig do
      params(
        column_name: T.nilable(T.any(String, Symbol)),
        block: T.nilable(T.proc.params(record: T.untyped).returns(T.untyped))
      ).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)])
    end
    def sum(column_name = nil, &block); end
  end

  class PrivateRelationWhereChain
    Elem = type_member { { fixed: ::TenantTheme } }

    sig { params(args: T.untyped).returns(PrivateRelation) }
    def associated(*args); end

    sig { params(args: T.untyped).returns(PrivateRelation) }
    def missing(*args); end

    sig { params(opts: T.untyped, rest: T.untyped).returns(PrivateRelation) }
    def not(opts, *rest); end
  end
end
