# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserArea::ApplicationController`.
# Please instead update this file by running `bin/tapioca dsl UserArea::ApplicationController`.


class UserArea::ApplicationController
  sig { returns(HelperProxy) }
  def helpers; end

  module HelperMethods
    include ::Turbo::DriveHelper
    include ::Turbo::FramesHelper
    include ::Turbo::IncludesHelper
    include ::Turbo::StreamsHelper
    include ::ActionView::Helpers::CaptureHelper
    include ::ActionView::Helpers::OutputSafetyHelper
    include ::ActionView::Helpers::TagHelper
    include ::Turbo::Streams::ActionHelper
    include ::ActionText::ContentHelper
    include ::ActionText::TagHelper
    include ::ViteRails::TagHelpers
    include ::ActionController::Base::HelperMethods
    include ::ApplicationHelper
    include ::LexicalHelper
    include ::RulerArea::ApplicationHelper
    include ::SvgHelper
    include ::UserArea::ContentFieldHelper
    include ::UserArea::CustomVariablesHelper
    include ::UserArea::ExternalUrlsHelper
    include ::UserArea::SiteSettingsHelper
    include ::ApplicationController::HelperMethods

    sig { returns(T.nilable(::Tenant)) }
    def current_tenant; end

    sig { returns(T.nilable(::User)) }
    def current_user; end

    sig { returns(T::Boolean) }
    def user_signed_in?; end
  end

  class HelperProxy < ::ActionView::Base
    include HelperMethods
  end
end
