# ==============================================================================
# config - database
# ==============================================================================
default: &default
  adapter: postgresql
  encoding: unicode
  user: <%= ENV['POSTGRES_USER'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5).to_i * ENV.fetch('RAILS_WORKERS', 1).to_i %>
  port: 5432

development:
  <<: *default
  host: <%= ENV['POSTGRES_HOST'] %>
  database: haguruma_development

test:
  <<: *default
  host: <%= ENV['POSTGRES_TEST_HOST'] || ENV['POSTGRES_HOST'] %>
  database: haguruma_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 50

staging:
  <<: *default
  host: <%= ENV['POSTGRES_HOST'] %>
  database: haguruma_staging

qa:
  <<: *default
  host: <%= ENV['POSTGRES_HOST'] %>
  database: haguruma_qa

production:
  <<: *default
  host: <%= ENV['POSTGRES_HOST'] %>
  database: haguruma_production