# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RulerArea::ApplicationController`.
# Please instead update this file by running `bin/tapioca dsl RulerArea::ApplicationController`.

class RulerArea::ApplicationController
  include GeneratedPathHelpersModule
  include GeneratedUrlHelpersModule
end