# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserArea::Alpha::RootController`.
# Please instead update this file by running `bin/tapioca dsl UserArea::Alpha::RootController`.


class UserArea::Alpha::RootController
  sig { returns(HelperProxy) }
  def helpers; end

  module HelperMethods
    include ::Turbo::DriveHelper
    include ::Turbo::FramesHelper
    include ::Turbo::IncludesHelper
    include ::Turbo::StreamsHelper
    include ::ActionView::Helpers::CaptureHelper
    include ::ActionView::Helpers::OutputSafetyHelper
    include ::ActionView::Helpers::TagHelper
    include ::Turbo::Streams::ActionHelper
    include ::ActionText::ContentHelper
    include ::ActionText::TagHelper
    include ::ViteRails::TagHelpers
    include ::ActionController::Base::HelperMethods
    include ::ApplicationHelper
    include ::LexicalHelper
    include ::RulerArea::ApplicationHelper
    include ::SvgHelper
    include ::UserArea::ContentFieldHelper
    include ::UserArea::ExternalUrlsHelper
    include ::UserArea::SiteSettingsHelper
    include ::ApplicationController::HelperMethods
    include ::UserArea::ApplicationController::HelperMethods

    sig { returns(T.nilable(::String)) }
    def current_blog_category; end

    sig { params(entry: ::ContentEntry).returns(T::Boolean) }
    def entry_authorized?(entry); end
  end

  class HelperProxy < ::ActionView::Base
    include HelperMethods
  end
end
