region: ap-northeast-1
cluster: haguruma-worker-prod
service: haguruma-main-service-eventbridge-poller-prod
service_definition: ecs-service-def.json
task_definition: ecs-task-def.jsonnet
timeout: "10m0s"
